### ISSUE TITLE
Build error in Hydro 

### ISSUE THREAD

**Issue by amiltonwong** [lrse/sptam#1]
Hi, @taihup,

My test machine is Ubuntu 12.04, ROS Hydro.

After running command:  catkin_make --pkg sptam -DSHOW_TRACKED_FRAMES=ON
It failed in building as follows:
# 
#### 
#### 

Scanning dependencies of target sptam
[  0%] [ 10%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/Camera.cpp.o
Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/MapMaker.cpp.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: **\* [sptam/src/sptam/CMakeFiles/sptam.dir/Camera.cpp.o] Error 1
make[2]: **\* Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option ‘-std=c++11’
make[2]: **\* [sptam/src/sptam/CMakeFiles/sptam.dir/MapMaker.cpp.o] Error 1
make[1]: **\* [sptam/src/sptam/CMakeFiles/sptam.dir/all] Error 2
make: **\* [all] Error 2
Invoking "make" failed
# 

Is it necessary to install it using ROS Indigo? Or there are some way to fix ‘-std=c++11’ error?

Thanks ~

Milton

**Comment by taihup** [comment]
It is work with Indigo (we tested it). However, you can try to update your compiler. Looks these thread, maybe they can help you: http://stackoverflow.com/questions/14674597/cc1plus-error-unrecognized-command-line-option-std-c11-with-g

https://github.com/gareth-cross/rviz_satellite/issues/1

Taihú

**Comment by amiltonwong** [comment]
Hi, Taihú,

Thanks for your suggestion. Finally I switch into installing gcc4.7 and g++ 4.7 and configuring 4.7 as default gcc.
ref: http://askubuntu.com/questions/113291/how-do-i-install-gcc-4-7

Then,  I install the currently newest version boost 1.59.

And finally build package sptam with success :)

**Comment by taihup** [comment]
Great!, let me know if you have some problem when you run it.

Taihú

**Comment by pangfumin** [comment]
hi ,amiltonwong. Thx for you answer about gcc-4.7.
I meet trouble when update my boost . my current version is 1.46. how can I update it to 1.59.

**Comment by amiltonwong** [comment]
Hi, @pangfumin ,
Not update, just compile and then install the newest version boost 1.59.
