### ISSUE TITLE
What's the new modification according to KITTI leaderboard

### ISSUE THREAD

**Issue by amiltonwong** [lrse/sptam#11]
Hi, @taihup ,

According to current KITTI leaderboard: http://www.cvlibs.net/datasets/kitti/eval_odometry.php ,
the S-PTAM performance is improved to 1.19% from previous 1.35%, could you tell us what are the modifications compared with previous one?

Thanks~
Milton

**Comment by tomifischer** [comment]
Jajaja bien ahí. Y para a que subamos la trayectoria final.

**Comment by taihup** [comment]
Hi Milton, We did several improvements. Among them we can mention:
- Loop closure to improve global localization and Map correction
- Covisibility Map to improve frustum culling and Local Bundle Adjustment
- OpenCV3 is supported
- correct some Bugs

However, we are still developing the new release of S-PTAM. So, it is
possible that take a while to upload it.

Best!

Taihú

**Comment by amiltonwong** [comment]
Hi, Taihú,
It's so glad to notice your improvement :)
Keep moving forward!

Best~
Milton
