### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by jacky70010** [lrse/sptam#15]
Hi~ 
 I was running STANDALONE
I got tracked frames, but where can I see map results ?

Regards~,

**Comment by taihup** [comment]
Hi jacky70010,

In standalone mode it is not possible to see the reconstructed Map. Only ROS version could be used to see the reconstructed map. However, you can extend s-ptam with some code to visualize it, for example using the pcl library.

**Comment by jacky70010** [comment]
Thaks for your help!    
It helps a lot.
