### ISSUE TITLE
error in launching node and ROS path

### ISSUE THREAD

**Issue by Rnandani** [lrse/sptam#2]
ERROR: cannot launch node of type [ros_utils/pose_to_path]: ros_utils
ROS path [0]=/opt/ros/indigo/share/ros
ROS path [1]=/home/mobilerobot/catkin_ws/src
ROS path [2]=/opt/ros/indigo/share
ROS path [3]=/opt/ros/indigo/stacks

Even though i am able to run kitti.launch file, i am getting above error.

**Comment by taihup** [comment]
Yes, it is a mistake that I did, I forgot to upload that node. It is just a node to visulize the trajectory path in rviz. I will upload it in the next weeks. But S-PTAM works without it.

**Comment by Rnandani** [comment]
I am ran kitti seq-00 for 6 times and got significant difference from the ground truth everytime. The poses were significantly different from the previous run also. Can you possibly guide me if i am missing anything. 
![sptam run1 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003971/92f4fb54-84ad-11e5-986d-5a63ad649eb5.jpg)
![sptam run3 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003976/92fb6e94-84ad-11e5-9a1e-8d2b0e5e412a.jpg)
![sptam run4 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003973/92f8b76c-84ad-11e5-8056-3292901ad978.jpg)
![sptam run5 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003974/92f9bf4a-84ad-11e5-8189-df437db5c626.jpg)
![sptam run6 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003972/92f6a684-84ad-11e5-8290-304373a0dfbc.jpg)
![sptam run7 for kittin seq-00](https://cloud.githubusercontent.com/assets/12201878/11003975/92facc3c-84ad-11e5-943c-b56a27f8432c.jpg)

**Comment by taihup** [comment]
You must have similar results for each run. Don't visualize anything, you must uses an i7 core, and compile by yourself g2o. When s-ptam has finished plot the estimated poses from the log file, and they must be similar. Does it help?

**Comment by Rnandani** [comment]
Yes..thanks!!

**Comment by ffntl** [comment]
Hi, I have the same ros_utils error, where did you find the ROS package ?

**Comment by taihup** [comment]
ros_utils is a node developed by us. we use ros_utils for plot the camera trajectory in rviz, basically it collects all the poses published by S-PTAM and creates a path message to be shown by rviz. We are full of work these days, so we can not assure you that we are going to public ros_utils package soon.

**Comment by Carrie0416** [comment]
Hi, I have the same ros_utils error, could you provider the this package ?

**Comment by taihup** [comment]
@Carrie0416, We uploaded the ros-utils package in [https://github.com/lrse/ros-utils](https://github.com/lrse/ros-utils). I hope it helps.
