### ISSUE TITLE
The Installation steps were not detailed enough. Could you explain them further?

### ISSUE THREAD

**Issue by YiChenCityU** [lrse/sptam#21]

**Comment by taihup** [comment]
Which step is not clear in particular?

**Comment by YiChenCityU** [comment]
I always meet some errors like this  when I _catkin_make_ as your instructions. I have installed opencv 3.3.1 and opencv_contrib 3.3.1。Is there any solvers? Thanks very much. 

make[2]: *** No rule to make target `opencv_calib3d-NOTFOUND', needed by `/home/eason/SPTAM_ws/devel/lib/libsptam.so'.  Stop.
make[1]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/all] Error 2
make: *** [all] Error 2

**Comment by YiChenCityU** [comment]
I have already installed the opencv and contrib with same version.

**Comment by taihup** [comment]
I recommend you to remove OpenCV and install ROS Kinetic. ROS will install OpenCV by itself.

**Comment by YiChenCityU** [comment]
Hi, @taihup  I gave up to build ros package and succeeded in building standAlone files. But where can I find "/bow_voc/DBoW2/brief_mit_malaga_vocabulary.yml.gz" file? Thanks very much.

**Comment by taihup** [comment]
The error that you mention is related to the Loop Closure module. First of all, compile S-PTAM without Loop Closure module. Once it is working, you can enable it. You can download the vocabulary from [https://github.com/lrse/bow_vocabularies/tree/master/DBoW2](https://github.com/lrse/bow_vocabularies/tree/master/DBoW2)

**Comment by YiChenCityU** [comment]
@taihup  Sorry to bother you. I have encountered this error. I cannot find answers in the internet. This is the cmake and make details:
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DSHOW_TRACKED_FRAMES=ON -DUSE_LOOPCLOSURE=ON -DSHOW_PROFILING=ON
Selected BUILD_TYPE: Release
-- Found Intel TBB
-- Enabling parallel code
-- Setting OpenCV threads to: 4
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   regex
-- Eigen found (include: /usr/local/include/eigen3)
opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_shapeopencv_stitchingopencv_superresopencv_videoopencv_videoioopencv_videostabopencv_vizopencv_arucoopencv_bgsegmopencv_bioinspiredopencv_ccalibopencv_datasetsopencv_dpmopencv_faceopencv_freetypeopencv_fuzzyopencv_img_hashopencv_line_descriptoropencv_optflowopencv_phase_unwrappingopencv_plotopencv_regopencv_rgbdopencv_saliencyopencv_sfmopencv_stereoopencv_structured_lightopencv_surface_matchingopencv_textopencv_trackingopencv_xfeatures2dopencv_ximgprocopencv_xobjdetectopencv_xphoto
-- Using CATKIN_DEVEL_PREFIX: /home/eason/Downloads/sptam-master/src/standAlone/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/eason/Downloads/sptam-master/src/standAlone/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eason/Downloads/sptam-master/src/standAlone/build
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ make 
Scanning dependencies of target frameGenerator
[  2%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/FileSequenceFrameGenerator.cpp.o
[  4%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/VideoFileFrameGenerator.cpp.o
[  7%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/ListOfFilesFrameGenerator.cpp.o
Linking CXX shared library libframeGenerator.so
[  7%] Built target frameGenerator
Scanning dependencies of target sptam-stereo
[  9%] Building CXX object CMakeFiles/sptam-stereo.dir/sptam-stereo.cpp.o
[ 12%] Building CXX object CMakeFiles/sptam-stereo.dir/KITTIGroundTruth.cpp.o
[ 14%] Building CXX object CMakeFiles/sptam-stereo.dir/SptamWrapper.cpp.o
[ 17%] Building CXX object CMakeFiles/sptam-stereo.dir/utils/ProgramOptions.cpp.o
[ 19%] Building CXX object CMakeFiles/sptam-stereo.dir/Timestamps.cpp.o
[ 21%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/CameraPose.cpp.o
[ 24%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/ImageFeatures.cpp.o
[ 26%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoGraph.cpp.o
[ 29%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/tracker_g2o.cpp.o
[ 31%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/match_to_points.cpp.o
[ 34%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Camera.cpp.o
[ 36%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Frame.cpp.o
[ 39%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Measurement.cpp.o
[ 41%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/g2o_driver.cpp.o
[ 43%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FrustumCulling.cpp.o
[ 46%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/sptam.cpp.o
[ 48%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MotionModel.cpp.o
[ 51%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FeatureExtractorThread.cpp.o
[ 53%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMaker.cpp.o
[ 56%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/RowMatcher.cpp.o
[ 58%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/TrackerViewStereo.cpp.o
[ 60%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapPoint.cpp.o
[ 63%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/BundleDriver.cpp.o
[ 65%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoFrame.cpp.o
[ 68%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMakerThread.cpp.o
[ 70%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/types_sba_extension.cpp.o
[ 73%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/pose_covariance.cpp.o
[ 75%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/projection_derivatives.cpp.o
[ 78%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/CovisibilityGraph.cpp.o
[ 80%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/timer.cpp.o
[ 82%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/draw/Draw.cpp.o
[ 85%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/log/Logger.cpp.o
[ 87%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/LoopClosing.cpp.o
[ 90%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/SmoothEstimatePropagator.cpp.o
[ 92%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/PoseEstimator.cpp.o
[ 95%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/StereoMatcher.cpp.o
[ 97%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp.o
[100%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/FBRISK.cpp.o
Linking CXX executable sptam-stereo
[100%] Built target sptam-stereo
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ ./sptam-stereo /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti.yaml /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti_cam_00_to_02_13_to_21.yaml /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_0/ /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_1/ dir --timestamps /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/times.txt 
*** Error in `./sptam-stereo': double free or corruption (out): 0x0000000001252740 ***
Aborted (core dumped)

**Comment by YiChenCityU** [comment]
@taihup  Sorry to bother you. I have encountered this error. I cannot find answers in the internet. This is the cmake and make details:

eason@eason:~/Downloads/sptam-master/src/standAlone/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DSHOW_TRACKED_FRAMES=ON -DUSE_LOOPCLOSURE=ON -DSHOW_PROFILING=ON
Selected BUILD_TYPE: Release
-- Found Intel TBB
-- Enabling parallel code
-- Setting OpenCV threads to: 4
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   regex
-- Eigen found (include: /usr/local/include/eigen3)
opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_shapeopencv_stitchingopencv_superresopencv_videoopencv_videoioopencv_videostabopencv_vizopencv_arucoopencv_bgsegmopencv_bioinspiredopencv_ccalibopencv_datasetsopencv_dpmopencv_faceopencv_freetypeopencv_fuzzyopencv_img_hashopencv_line_descriptoropencv_optflowopencv_phase_unwrappingopencv_plotopencv_regopencv_rgbdopencv_saliencyopencv_sfmopencv_stereoopencv_structured_lightopencv_surface_matchingopencv_textopencv_trackingopencv_xfeatures2dopencv_ximgprocopencv_xobjdetectopencv_xphoto
-- Using CATKIN_DEVEL_PREFIX: /home/eason/Downloads/sptam-master/src/standAlone/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/eason/Downloads/sptam-master/src/standAlone/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eason/Downloads/sptam-master/src/standAlone/build
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ make 
Scanning dependencies of target frameGenerator
[  2%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/FileSequenceFrameGenerator.cpp.o
[  4%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/VideoFileFrameGenerator.cpp.o
[  7%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/ListOfFilesFrameGenerator.cpp.o
Linking CXX shared library libframeGenerator.so
[  7%] Built target frameGenerator
Scanning dependencies of target sptam-stereo
[  9%] Building CXX object CMakeFiles/sptam-stereo.dir/sptam-stereo.cpp.o
[ 12%] Building CXX object CMakeFiles/sptam-stereo.dir/KITTIGroundTruth.cpp.o
[ 14%] Building CXX object CMakeFiles/sptam-stereo.dir/SptamWrapper.cpp.o
[ 17%] Building CXX object CMakeFiles/sptam-stereo.dir/utils/ProgramOptions.cpp.o
[ 19%] Building CXX object CMakeFiles/sptam-stereo.dir/Timestamps.cpp.o
[ 21%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/CameraPose.cpp.o
[ 24%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/ImageFeatures.cpp.o
[ 26%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoGraph.cpp.o
[ 29%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/tracker_g2o.cpp.o
[ 31%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/match_to_points.cpp.o
[ 34%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Camera.cpp.o
[ 36%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Frame.cpp.o
[ 39%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Measurement.cpp.o
[ 41%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/g2o_driver.cpp.o
[ 43%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FrustumCulling.cpp.o
[ 46%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/sptam.cpp.o
[ 48%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MotionModel.cpp.o
[ 51%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FeatureExtractorThread.cpp.o
[ 53%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMaker.cpp.o
[ 56%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/RowMatcher.cpp.o
[ 58%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/TrackerViewStereo.cpp.o
[ 60%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapPoint.cpp.o
[ 63%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/BundleDriver.cpp.o
[ 65%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoFrame.cpp.o
[ 68%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMakerThread.cpp.o
[ 70%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/types_sba_extension.cpp.o
[ 73%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/pose_covariance.cpp.o
[ 75%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/projection_derivatives.cpp.o
[ 78%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/CovisibilityGraph.cpp.o
[ 80%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/timer.cpp.o
[ 82%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/draw/Draw.cpp.o
[ 85%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/log/Logger.cpp.o
[ 87%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/LoopClosing.cpp.o
[ 90%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/SmoothEstimatePropagator.cpp.o
[ 92%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/PoseEstimator.cpp.o
[ 95%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/StereoMatcher.cpp.o
[ 97%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp.o
[100%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/FBRISK.cpp.o
Linking CXX executable sptam-stereo
[100%] Built target sptam-stereo
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ ./sptam-stereo /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti.yaml /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti_cam_00_to_02_13_to_21.yaml /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_0/ /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_1/ dir --timestamps /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/times.txt 
*** Error in `./sptam-stereo': double free or corruption (out): 0x0000000001252740 ***
Aborted (core dumped)

**Comment by YiChenCityU** [comment]
@taihup Sorry to bother you. I have encountered this error. I cannot find answers in the internet. This is the cmake and make details. 

`eason@eason:~/Downloads/sptam-master/src/standAlone/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DSHOW_TRACKED_FRAMES=ON -DUSE_LOOPCLOSURE=ON -DSHOW_PROFILING=ON
Selected BUILD_TYPE: Release
-- Found Intel TBB
-- Enabling parallel code
-- Setting OpenCV threads to: 4
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   thread
--   regex
-- Eigen found (include: /usr/local/include/eigen3)
opencv_calib3dopencv_coreopencv_dnnopencv_features2dopencv_flannopencv_highguiopencv_imgcodecsopencv_imgprocopencv_mlopencv_objdetectopencv_photoopencv_shapeopencv_stitchingopencv_superresopencv_videoopencv_videoioopencv_videostabopencv_vizopencv_arucoopencv_bgsegmopencv_bioinspiredopencv_ccalibopencv_datasetsopencv_dpmopencv_faceopencv_freetypeopencv_fuzzyopencv_img_hashopencv_line_descriptoropencv_optflowopencv_phase_unwrappingopencv_plotopencv_regopencv_rgbdopencv_saliencyopencv_sfmopencv_stereoopencv_structured_lightopencv_surface_matchingopencv_textopencv_trackingopencv_xfeatures2dopencv_ximgprocopencv_xobjdetectopencv_xphoto
-- Using CATKIN_DEVEL_PREFIX: /home/eason/Downloads/sptam-master/src/standAlone/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/eason/Downloads/sptam-master/src/standAlone/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.19
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eason/Downloads/sptam-master/src/standAlone/build
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ make 
Scanning dependencies of target frameGenerator
[  2%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/FileSequenceFrameGenerator.cpp.o
[  4%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/VideoFileFrameGenerator.cpp.o
[  7%] Building CXX object CMakeFiles/frameGenerator.dir/FrameGenerator/ListOfFilesFrameGenerator.cpp.o
Linking CXX shared library libframeGenerator.so
[  7%] Built target frameGenerator
Scanning dependencies of target sptam-stereo
[  9%] Building CXX object CMakeFiles/sptam-stereo.dir/sptam-stereo.cpp.o
[ 12%] Building CXX object CMakeFiles/sptam-stereo.dir/KITTIGroundTruth.cpp.o
[ 14%] Building CXX object CMakeFiles/sptam-stereo.dir/SptamWrapper.cpp.o
[ 17%] Building CXX object CMakeFiles/sptam-stereo.dir/utils/ProgramOptions.cpp.o
[ 19%] Building CXX object CMakeFiles/sptam-stereo.dir/Timestamps.cpp.o
[ 21%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/CameraPose.cpp.o
[ 24%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/ImageFeatures.cpp.o
[ 26%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoGraph.cpp.o
[ 29%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/tracker_g2o.cpp.o
[ 31%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/match_to_points.cpp.o
[ 34%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Camera.cpp.o
[ 36%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Frame.cpp.o
[ 39%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/Measurement.cpp.o
[ 41%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/g2o_driver.cpp.o
[ 43%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FrustumCulling.cpp.o
[ 46%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/sptam.cpp.o
[ 48%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MotionModel.cpp.o
[ 51%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/FeatureExtractorThread.cpp.o
[ 53%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMaker.cpp.o
[ 56%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/RowMatcher.cpp.o
[ 58%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/TrackerViewStereo.cpp.o
[ 60%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapPoint.cpp.o
[ 63%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/BundleDriver.cpp.o
[ 65%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/StereoFrame.cpp.o
[ 68%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/MapMakerThread.cpp.o
[ 70%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/types_sba_extension.cpp.o
[ 73%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/pose_covariance.cpp.o
[ 75%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/projection_derivatives.cpp.o
[ 78%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/CovisibilityGraph.cpp.o
[ 80%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/timer.cpp.o
[ 82%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/draw/Draw.cpp.o
[ 85%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/utils/log/Logger.cpp.o
[ 87%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/LoopClosing.cpp.o
[ 90%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/SmoothEstimatePropagator.cpp.o
[ 92%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/PoseEstimator.cpp.o
[ 95%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/StereoMatcher.cpp.o
[ 97%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp.o
[100%] Building CXX object CMakeFiles/sptam-stereo.dir/home/eason/Downloads/sptam-master/src/sptam/loopclosing/detectors/FBRISK.cpp.o
Linking CXX executable sptam-stereo
[100%] Built target sptam-stereo
eason@eason:~/Downloads/sptam-master/src/standAlone/build$ ./sptam-stereo /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti.yaml /home/eason/SPTAM_ws/src/sptam/configurationFiles/kitti_cam_00_to_02_13_to_21.yaml /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_0/ /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/image_1/ dir --timestamps /home/eason/Desktop/KITTI\ Dataset/dataset/sequences/10/times.txt 
*** Error in `./sptam-stereo': double free or corruption (out): 0x0000000001252740 ***
Aborted (core dumped)
`

**Comment by taihup** [comment]
Hi, I can't understand the error. try to remove everything from build directory and run cmakee and make commands again. Use the flag -DUSE_LOOPCLOSURE=OFF first. Then, if S-PTAM works, try enable it.
