### ISSUE TITLE
I still got a error never meet before. Does anyone successfully build this project? Please help me. 

### ISSUE THREAD

**Issue by YiChenCityU** [lrse/sptam#22]
I got this problem when I run this :  
`roslaunch sptam mit.launch`

`[ERROR] [1513921915.103911788]: Failed to load nodelet [/sptam] of type [sptam/sptam_nodelet] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type sptam::sptam_nodelet as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1513921915.103948410]: The error before refreshing the cache was: Failed to load library /home/eason/sptam_ws/devel/lib//libsptam_nodelet.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /home/eason/sptam_ws/devel/lib/libsptam.so: undefined symbol: _ZTIN3g2o9VertexCamE)
`
Does anyone successfully build this project or solve this problem? Please help me.

**Comment by taihup** [comment]
Send me the compilation output of catkin_make command. Check that sptam_nodelet was compiled successfully. Try with the KITTI dataset instead of MIT. Be sure tofollow all the steps mention in the README. If you are not a ROS user, use the standAlone version of S-PTAM.
