### ISSUE TITLE
Error Evaluation code

### ISSUE THREAD

**Issue by YiChenCityU** [lrse/sptam#23]
Hi， Irse, do you have the sample code about the error evaluation part ? I also want to test the performance of this SLAM.
Thanks very much.

**Comment by tomifischer** [comment]
Hello Yi Chen,

Im sorry but for now you will have to code the error evaluation script yourself. For references on the method please refer to [1] (see eq. 1). It is really just a matter of parsing the pose outputs and doing some simple linear operations.

Best,
T. Fischer

[1] “Stereo Vision-Based Localization for Hexapod Walking Robots Operating in Rough Terrains”,
Thomas Fischer, Taihú Pire, Petr Cizek, Pablo De Cristóforis, Jan Faigl. 2016 IEEE/RSJ
International Conference on Intelligent Robots and Systems (IROS).
