### ISSUE TITLE
kitti rosbag doesn't exist

### ISSUE THREAD

**Issue by breyner-posso** [lrse/sptam#24]
Hi, I'm new using S-PTAM. I installed and tested it using mit and EuRoc Mav Datasets. However I'd like to test it using kitti datset but rosbag isn't available. Could you give me some advice, please? I've seen some scripts to convert kiiti dataset to rosbag but I don't know if that is the right way (or which one could work). Moreover I have a dataset that was taken with our stereo camera system and I'd like to test it too, but I don't know how to set a .launch file for our dataset, could you give me some advice, please?

Thaks a lot for your help!

**Comment by taihup** [comment]
Hi Breyner, I will fix the KITTI dataset rosbag link as soon as possible. It is not hard to convert the kitti dataset to rosbag. The resulting rosbag should contains the left and right images and the cameraInfo message for each camera. You can try [https://github.com/lrse/dataset2bag](https://github.com/lrse/dataset2bag) script to generate de rosbag.

You must learn ROS to understand how to create your own launch file. You can check the existing launch files that we provide in the s-ptam package to have an idea of the form that it should have.

**Comment by taihup** [comment]
I updated the KITTI rosbag link, so you can download it now.

**Comment by breyner-posso** [comment]
Tks a lot!

**Comment by breyner-posso** [comment]
Hi, I tested kitti dataset and it worked well. Now I'm trying to run my own dataset. I'm publishing the topics CameraInfo and Image for left and right cameras. I edited a launch file (kitti.launch) and ran sptam. The sptam node is reading the topics (I saw it using rqt)

![rosgraph_acfr](https://user-images.githubusercontent.com/34694863/35209580-d87d9858-ffa2-11e7-97ba-0c77d60596eb.png)

But nothing happens and when I try to see the stereo images being processed by sptam (using rviz), it shows NO IMAGES (in fact it doesn't show any image). I don't know if the format of the images that my node publish is right (rectified and in color), because the images published in kitti example are rectified but in gray scale.

Thanks a lot for your help!

**Comment by taihup** [comment]
S-PTAM works with color and grey scale images. Check that you compile with
the-DSHOW_TRACKED_FRAMES=ON option? Please, paste here the terminal output
of S-PTAM and the generated logfile in ~/.ros directory. Moreover, show me
the stereo images rectified that S-PTAM is taking as input. What camera
model are you using? if you are working with your camera in live mode and
it is not a dataset, remove from your .launch file the command rosparam set
use_sim_time true, and run in your terminal rosparam set_use_sim_time false.

**Comment by breyner-posso** [comment]
Hi, tks a lot for your help. Before send you the information that you have asked me, I would like to know what this error means and how to solve it.

acfr@acfr-protea:~/catkin_ws/src/sptam-master/launch$ roslaunch sptam kitti.launch
... logging to /home/acfr/.ros/log/539bb514-0161-11e8-a3ef-b8ca3a8203b2/roslaunch-acfr-protea-27828.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://acfr-protea:43403/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/acfr/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[start_broadcaster-1]: started with pid [27845]
process[sptam_path-2]: started with pid [27846]
process[sptam-3]: started with pid [27865]
**[ERROR] [1516841697.764833967]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/gmapping/nodelet_plugins.xml' has no Root Element. This likely means the XML is malformed or missing..**
[ INFO] [1516841697.775219669]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0

I look into that folder and that file doesn't exist. What can I do?

Tks a lot for your help!

**Comment by breyner-posso** [comment]
Hi! When I run kitti dataset and my dataset (the camera is a NVidia with 100°FOV) I found two main differences:

1. The initialization.
* With kitti dataset:

[ INFO] [1516855339.401167307]: Loop Detector initializing, loading vocabulary
[ INFO] [1516855346.626983834, 1385798162.985444388]: init calib
[ INFO] [1516855346.627137313, 1385798162.985444388]: baseline: 0.537166
[ INFO] [1516855346.672563241, 1385798163.025699568]: S-PTAM stereo node initialized.

*With my datset

[ INFO] [1516853407.970888568]: Loop Detector initializing, loading vocabulary
[ INFO] [1516853415.451132111]: S-PTAM stereo node initialized.

And then it stops and do nothing. As we can see neither init calib nor baselines steps are done.

2. /tf topic
* kitti dataset publishes this topic and sptam node is suscribed. What is it about?

![rosgraph_kitti](https://user-images.githubusercontent.com/34694863/35371209-d92b264e-01e6-11e8-9e4e-26483c57c313.png)

* with my dataset
![acfr-sptam_nodes](https://user-images.githubusercontent.com/34694863/35371261-199697fe-01e7-11e8-9451-ec7b2dd5662f.png)

These are two rectified images that are being published:

![dataset_image](https://user-images.githubusercontent.com/34694863/35371336-9cc154ca-01e7-11e8-9212-28d5797944bd.png)

I compile with the option -DSHOW_TRACKED_FRAMES=ON.

What .log file should I show you?

Tks a lot for all your help!

**Comment by taihup** [comment]
Check that your camera is publishing time synchronised topics. Are
image_color rectified images? I think they aren´t. So, in your launch file,
it looks like you are not subscribing to rectified image topics. You must
use stereo_image_proc <http://wiki.ros.org/stereo_image_proc> to rectified
the image topics on ROS. Did you calibrate the camera? If not use the stereo
calibration ROS package
<http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration>.

You will find S-PTAM named <date_and_time_of_running>.log file in ~/.ros/
directory. However, to generated this .log file you should pass
-DSHOW_PROFILING=ON flag to cmake

**Comment by hlezki** [comment]
Hello, 
Can you please share kitti rosbag files again. I could not download it. I think the link is broken. I tried to use 2 different converter in order to convert synhronized Kitti images into rosbag files with the following algorithms
1. https://github.com/lrse/dataset2bag 
2. https://github.com/ethz-asl/kitti_to_rosbag 

I created this rosbags to pulish following topics;
/kitti_stereo/left/image_rect
/kitti_stereo/right/image_rect
/kitti_stereo/left/camera_info 
/kitti_stereo/right/camera_info

However, SPTAM algorithm stucked into "S-PTAM stereo node initialized". It does not continue processing. I also checked log file, it does not contain any pose information such as refined camera pose. On the other hand, for Euroc dataset i can run the code and i can reach the pose informations. So, the problem is related with the kitti bag files and/or kitti launch file. 
Please can you share your kitti rosbag files again, the link is broken. 
Thank you

**Comment by taihup** [comment]
Hi hlezki, our server with the sequences is down because a hardware issue and there is non personal working to fix it because the quarantine.

the topics look fine, maybe the image or the camera_info message  are corrupted. Have you checked them? try printing the message information with rostopic echo and use rqt to visualize the images.
