### ISSUE TITLE
Error Running S-PTAM with kitti_00.bag

### ISSUE THREAD

**Issue by breyner-posso** [lrse/sptam#26]
Hi, I'm trying to run S-PTAM usign kitti_00.bag and I got two errors, could you help me to fix them, please? Thanks a lot in advanced!

acfr@acfr-protea:~/catkin_ws/src/sptam-master/launch$ roslaunch sptam kitti.launch
... logging to /home/acfr/.ros/log/97f88d3c-063d-11e8-be02-b8ca3a8203b2/roslaunch-acfr-protea-25878.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://acfr-protea:44969/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/acfr/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[start_broadcaster-1]: started with pid [25896]
process[sptam_path-2]: started with pid [25897]
process[sptam-3]: started with pid [25915]
**[ERROR] [1517372240.668652511]: Skipped loading plugin with error: XML Document '/opt/ros/kinetic/share/gmapping/nodelet_plugins.xml' has no Root Element. This likely means the XML is malformed or missing..**
[ INFO] [1517372240.901949235]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1517372243.114725293]: Loop Detector initializing, loading vocabulary
[ INFO] [1517372253.590275289]: S-PTAM stereo node initialized.
[ INFO] [1517372259.097301988]: init calib
[ INFO] [1517372259.097467046]: baseline: 0.537166
[ INFO] [1517372259.131948513]: Map initialized with 83 points.
[sptam-3] process has died [pid 25915, exit code -11, cmd /home/acfr/catkin_ws/devel/lib/sptam/sptam_node /stereo/left/image_rect:=/kitti_stereo/left/image_rect /stereo/right/image_rect:=/kitti_stereo/right/image_rect /stereo/left/camera_info:=/kitti_stereo/left/camera_info /stereo/right/camera_info:=/kitti_stereo/right/camera_info __name:=sptam __log:=/home/acfr/.ros/log/97f88d3c-063d-11e8-be02-b8ca3a8203b2/sptam-3.log].
log file: /home/acfr/.ros/log/97f88d3c-063d-11e8-be02-b8ca3a8203b2/sptam-3*.log

**Comment by taihup** [comment]
I think your first error is related to [https://github.com/ros-perception/slam_gmapping/pull/56](https://github.com/ros-perception/slam_gmapping/pull/56) and it is an issue of gmapping. 

Respect to the second error, please paste here the content of the generated .log that it is pointed out in the error message. Try to run several times S-PTAM, maybe it is something related to the initialisation of the node but I am not sure about it. It is look like S-PTAM crashed.
