### ISSUE TITLE
Not enough points to initialize map.

### ISSUE THREAD

**Issue by jacky70010** [lrse/sptam#27]
Hi, I am testing with my own bag (recorded by my zed camera)
In "aligned_vector<MapPoint> points "
point size is always zero 
I have tried the MIT Stata Center dataset and it works fine
by the way I am not using loop closure

this is what I got
... logging to /home/jacky/.ros/log/19749ac4-3265-11e8-a708-0800275b2bd8/roslaunch-jacky-VirtualBox-24302.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jacky-VirtualBox:44671/

SUMMARY
========

PARAMETERS
 * /imagetransport1/approximate_sync: True
 * /imagetransport1/queue_size: 1000
 * /imagetransport2/approximate_sync: True
 * /imagetransport2/queue_size: 1000
 * /rosdistro: kinetic
 * /rosversion: 1.12.7
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/jacky/catki...
 * /sptam/MatchingCellSize: 30
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: True
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/queue_size: 1000
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /stereo/stereo_image_proc/approximate_sync: True
 * /stereo/stereo_image_proc/queue_size: 1000
 * /use_sim_time: True

NODES
  /imagetransport2/
    republish (image_transport/republish)
  /stereo/
    stereo_image_proc (stereo_image_proc/stereo_image_proc)
  /imagetransport1/
    republish (image_transport/republish)
  /
    camera_broadcaster (tf2_ros/static_transform_publisher)
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[imagetransport1/republish-1]: started with pid [24364]
process[imagetransport2/republish-2]: started with pid [24365]
process[stereo/stereo_image_proc-3]: started with pid [24367]
process[camera_broadcaster-4]: started with pid [24383]
process[sptam_path-5]: started with pid [24417]
process[sptam-6]: started with pid [24462]
[ INFO] [1522227799.398858325]: Initializing nodelet with 1 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1522227802.802015569, 1514963975.211378596]: S-PTAM stereo node initialized.
[ INFO] [1522227807.322240749, 1514963976.115933562]: init calib
[ INFO] [1522227807.322738574, 1514963976.115933562]: baseline: 0.00012
[ INFO] [1522227807.812476321, 1514963976.212768105]: Trying to intialize map...
[ WARN] [1522227808.031914579, 1514963976.257170983]: Not enough points to initialize map.

last this is my rqt graph 
https://imgur.com/a/b9XBk

Hope you can help me 
 Best regards

**Comment by taihup** [comment]
your baseline is in wrong units. It should be something close to 0.12 (this
is 12 cm)

**Comment by jacky70010** [comment]
Thanks,
I checked my ZED camera the baseline is indeed 12cm
Sorry, I am new to camera. Do you know where I can change my baseline?
In the camera_info?

**Comment by taihup** [comment]
yes, you have to change that in the camera_info message.

**Comment by jacky70010** [comment]
Thanks a lot. 
I appreciate your reply!

**Comment by jacky70010** [comment]
Hi, I have fixed my baseline to 0.12 (which is the correct value)
but still couldn't get enough map points (I have checked the map points are between 0-3)
is there other problem that could lead to this issue

this is my camera info:
left_info
header: 
  seq: 30945
  stamp: 
    secs: 1514963977
    nsecs: 844533434
  frame_id: zed_left_camera
height: 720
width: 1280
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [673.9771118164062, 0.0, 646.008056640625, 0.0, 673.9771118164062, 387.2628173828125, 0.0, 0.0, 1.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [673.9771118164062, 0.0, 646.008056640625, 0.0, 0.0, 673.9771118164062, 387.2628173828125, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

-----------------------------------------------------------
right_info
header: 
  seq: 30800
  stamp: 
    secs: 1514963975
    nsecs: 334894665
  frame_id: zed_left_camera
height: 720
width: 1280
distortion_model: plumb_bob
D: [0.0, 0.0, 0.0, 0.0, 0.0]
K: [673.9771118164062, 0.0, 646.008056640625, 0.0, 673.9771118164062, 387.2628173828125, 0.0, 0.0, 1.0]
R: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
P: [673.9771118164062, 0.0, 646.008056640625, -80.87725937366486, 0.0, 673.9771118164062, 387.2628173828125, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False

**Comment by taihup** [comment]
Hi, are the camera images rectified? try to use [http://wiki.ros.org/stereo_image_proc](http://wiki.ros.org/stereo_image_proc) node to rectify the images. S-PTAM works with rectified cameras.

**Comment by jacky70010** [comment]
yes the image are rectified 
in my rosbag my image was  sensor_msgs/CompressedImage
so I use image_transport to transport to sensor_msgs/Image
and then use the stereo_image_proc node
this is my launch file 

[zed.launch.txt](https://github.com/lrse/sptam/files/1887487/zed.launch.txt)

**Comment by taihup** [comment]
Try to follow this launch. I did for my ZED camera. In this case the ZED camera was used with the VGA resolution configuration.
[zed_bag.launch.txt](https://github.com/lrse/sptam/files/1887488/zed_bag.launch.txt)

**Comment by jacky70010** [comment]
Could you show me what is in the zed_vga.yaml file ?
same as in the kitti.yaml?

**Comment by taihup** [comment]
I changed some parameters. Try also changing the EpipolarDistance to 1 or 2.
[zed_vga.yaml.txt](https://github.com/lrse/sptam/files/1889044/zed_vga.yaml.txt)

**Comment by jacky70010** [comment]
in my bag there is only
/image_raw_color/compressed
/image_rect_color/compressed
so I use image transport (which can only do on raw image)
to get /image_raw_color
then give /image_raw_color to stereo_image_proc
 however the node wants /image_raw
Is this could be a problem?

or maybe I could just use /image_rect_color/compressed ?

**Comment by taihup** [comment]
I think your launch is correct. I think is not properly tabulated (I can't remember now if launch files should be properly tabulated to work fine). Try to modified the configuration file that you are using. Did you try changing the EpipolarDistance parameter?

If you are working with a rosbag, remember to run the parameter set use_sim_time true after roscore command in terminal. Also, you should public the clock with the rosbag, like the datasets examples. You can also change the rate of publication to make sure that all the images are processed properly.
Summarizing, you should do in terminal:
```
roscore &
rosparam set use_sim_time true
rosbag play --clock rosbagFile.bag -r 0.2
```
Another issue could be that your camera calibration is not so good. I am seeing your camera_info messages and they are not looking good because you do not have distortion parameters D and you do not have rectification rotation matrix R set. Moreover, the frame_id of right camera is wrong.

**Comment by jacky70010** [comment]
Finally I successfully initialize map but get error about  covisibility keyframes
ERROR: There is not any covisibility keyframes observing the tracked points
which part should I look into?
thanks for all the help!!! 

[ INFO] [1523461133.908802132, 1514963977.477140960]: S-PTAM stereo node initialized.
[ INFO] [1523461138.793225855, 1514963979.920527447]: init calib
[ INFO] [1523461138.793459726, 1514963979.920527447]: baseline: 0.12
[ INFO] [1523461139.237742439, 1514963980.139035384]: Trying to intialize map...
[ INFO] [1523461139.415248260, 1514963980.229501520]: mappoint: [73]
[ INFO] [1523461139.422501930, 1514963980.234898885]: Map initialized with 73 points.
[ WARN] [1523461140.421120513, 1514963980.733720627]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1523461142.983779618, 1514963982.015061306]: Not enough points for tracking.

**Comment by taihup** [comment]
What was the problem?

If the camera is moving too fast, S-PTAM is going to lose the Localization.
Try to leave the camera still and then move it slowly to check if that is
the problem.

**Comment by jacky70010** [comment]
this error repeats
[WARN] [1523461140.421120513, 1514963980.733720627]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points

I will leave the camera still and try again!

**Comment by taihup** [comment]
I am askiing about the error that do not let S-PTAM initialize the map. How
do you solve it? because it could help to someone else.

**Comment by jacky70010** [comment]
in my bag there was 
/image_raw_color/compressed
/image_rect_color/compressed
at first I do on /image_raw_color/compressed use image transport and then get rectify image.

then I try directly do   image transport on /image_rect_color/compressed
(this is wrong about image transport could only do on raw images
http://wiki.ros.org/image_transport ) 
then get /image_rect_color  so I put it into sptam node directly
this is my final launch file!
[zedlaunch.txt](https://github.com/lrse/sptam/files/1899658/zedlaunch.txt)

**Comment by taihup** [comment]
Thanks for contribute ;)

**Comment by breyner-posso** [comment]
Hi, how do you solve this issue:

[WARN] [1523461140.421120513, 1514963980.733720627]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points

I'm getting something like that and no map is build.

Tks a lot for your advice.

**Comment by jacky70010** [comment]
Hi, are you trying the bag provided by the author or you are also working on zeds?

**Comment by jacky70010** [comment]
I saw your issue. 
My problem was my calibration wasn't pretty good, you could try to link features to see if the feature matches.
Or you could slow down your ros bag.
 Ex. rosbag play -r 0.2
By the way are you using stereo image proc?  Or using the opencv way to calibrate.

**Comment by breyner-posso** [comment]
Hi, I'm using my own dataset. Actually I'm running SPTAM but I'm not getting any map.

acfr@acfr-protea:~/catkin_ws$ roslaunch sptam acfr.launch
... logging to /home/acfr/.ros/log/dfde1f4a-4c10-11e8-b53e-b8ca3a8203b2/roslaunch-acfr-protea-24929.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://acfr-protea:44241/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/acfr/catkin...
 * /sptam/MatchingCellSize: 30
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /stereo/
    stereo_image_proc (stereo_image_proc/stereo_image_proc)
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)

ROS_MASTER_URI=http://localhost:11311

process[stereo/stereo_image_proc-1]: started with pid [24947]
process[sptam_path-2]: started with pid [24948]
process[sptam-3]: started with pid [24954]
[ INFO] [1525049625.405580944]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1525049625.555098245]: Loop Detector initializing, loading vocabulary
[ INFO] [1525049634.039631096]: S-PTAM stereo node initialized.
[ INFO] [1525049637.860779009]: init calib
[ INFO] [1525049637.860956353]: baseline: 0.584967
[ INFO] [1525049638.101483523]: Map initialized with 45 points.
[ WARN] [1525049638.682994378]: Not enough points for tracking.
[ WARN] [1525049640.929131143]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049654.157759622]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049660.745917501]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049661.825162811]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049665.856239203]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049670.135123189]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049681.202346129]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049691.770648229]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049701.210938574]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049703.515873901]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049705.108644473]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049710.716088369]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049711.660556581]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049716.751190998]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049718.063519255]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049718.360129805]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049720.990454635]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049740.064274117]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049740.265883895]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049742.313579714]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049744.302966236]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049756.077361346]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049758.880483230]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049762.325829975]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049770.864540302]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049771.151525750]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049773.199360329]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1525049773.898833449]: Not enough points for tracking.

Tks a lot for your advice.

**Comment by breyner-posso** [comment]
Hi! tks for your answers!
I'm using stereo_image_proc in order to publish undistorted and rectified stereo images.
I'm gonna try to slow down the bag file.
Tks! :)

**Comment by jacky70010** [comment]
Stereo image proc publishes point cloud
So you could use rviz to see that your rectification images are good or not!
