### ISSUE TITLE
Assertion `intrinsicLeft == intrinsicRight' failed.

### ISSUE THREAD

**Issue by breyner-posso** [lrse/sptam#28]
Hi, I'm trying to run S-PTAM with my own stereo calibrated and rectified data set but I'm getting this error and I really don't know what is wrong.
Thanks a lot for your help!

acfr@acfr-protea:~/catkin_ws/src/sptam-master/launch$ roslaunch sptam acfr.launch
... logging to /home/acfr/.ros/log/9acf877a-478f-11e8-ac7c-b8ca3a8203b2/roslaunch-acfr-protea-27477.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://acfr-protea:34237/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 2000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/acfr/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /stereo/
    stereo_image_proc (stereo_image_proc/stereo_image_proc)
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)

ROS_MASTER_URI=http://localhost:11311

process[stereo/stereo_image_proc-1]: started with pid [27495]
process[sptam_path-2]: started with pid [27501]
process[sptam-3]: started with pid [27514]
[ INFO] [1524554287.204671234]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 2000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 2000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1524554287.529219088]: Loop Detector initializing, loading vocabulary
[ INFO] [1524554296.426749743]: S-PTAM stereo node initialized.
[ INFO] [1524554297.009502797]: init calib
sptam_node: /home/acfr/catkin_ws/src/sptam-master/src/ros/stereo_driver.cpp:317: void sptam::stereo_driver::loadCameraCalibration(const CameraInfoConstPtr&, const CameraInfoConstPtr&): Assertion `intrinsicLeft == intrinsicRight' failed.
[sptam-3] process has died [pid 27514, exit code -6, cmd /home/acfr/catkin_ws/devel/lib/sptam/sptam_node /stereo/left/image_rect:=/stereo/left/image_rect /stereo/right/image_rect:=/stereo/right/image_rect /stereo/left/camera_info:=/gmsl/B3/camera_info /stereo/right/camera_info:=/gmsl/B2/camera_info robot/pose:=odom __name:=sptam __log:=/home/acfr/.ros/log/9acf877a-478f-11e8-ac7c-b8ca3a8203b2/sptam-3.log].
log file: /home/acfr/.ros/log/9acf877a-478f-11e8-ac7c-b8ca3a8203b2/sptam-3*.log

**Comment by taihup** [comment]
That means that the cameras are not rectified. At least, in the cameraInfo messages the rectification does not appear. If the cameras are rectified the intrinsic parameters inside the P matrix of cameraInfo messages should be the same.

**Comment by breyner-posso** [comment]
Hi! first of all, thanks a lot for your help. I fixed the problem and now I'm running S-PTAM with my own dataset, but I'm getting this:

acfr@acfr-protea:~/catkin_ws$ roslaunch sptam acfr.launch
... logging to /home/acfr/.ros/log/d3f4d29a-48e7-11e8-a52a-b8ca3a8203b2/roslaunch-acfr-protea-5190.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://acfr-protea:34699/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 2000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/acfr/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /stereo/
    stereo_image_proc (stereo_image_proc/stereo_image_proc)
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)

ROS_MASTER_URI=http://localhost:11311

process[stereo/stereo_image_proc-1]: started with pid [5208]
process[sptam_path-2]: started with pid [5209]
process[sptam-3]: started with pid [5217]
[ INFO] [1524702130.917324400]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 2000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 2000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1524702131.078567789]: Loop Detector initializing, loading vocabulary
[ INFO] [1524702139.255362110]: S-PTAM stereo node initialized.
[ INFO] [1524702148.291382720]: init calib
[ INFO] [1524702148.316342967]: baseline: 0.584967
[ INFO] [1524702148.937731023]: Map initialized with 34 points.
[ WARN] [1524702153.929021746]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702169.995521925]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702173.697949973]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702181.509765843]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702183.504044707]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702192.387926727]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702198.697397908]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702199.844781791]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702211.024708136]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702217.886760256]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702219.562904172]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702228.745723087]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702236.601386300]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702239.989759320]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1524702255.421210900]: Not enough points for tracking.

And at the end I didn't get any path.

What could I do?

Thaks a lot for all your support.

**Comment by taihup** [comment]
Which camera are you using? What is the camera baseline (distance between left and right camera)? Send me some sample images? Try to leave still the camera observing a high textured area. Check the issue  #27, #24 and #16

**Comment by breyner-posso** [comment]
Hi, tks a lot for your answer.
1. The cameras I'm using are SF3322 - Sekonix (100° FOV) (1920x1208)
2. Camera baseline is aprox. 58cm.
3. These are some sample images:

Left and Right Images (raw)
![image](https://user-images.githubusercontent.com/34694863/39412304-8461da1a-4c5d-11e8-8f52-4b1e5d091792.png)

Left and Right undistorted and rectified (stereo_before_refinement)
![image](https://user-images.githubusercontent.com/34694863/39412309-9fff6c4c-4c5d-11e8-817d-11dfef24b877.png)

Left and Right undistorted and rectified (stereo_after_refinement)
![image](https://user-images.githubusercontent.com/34694863/39412385-ff1fb2b2-4c5e-11e8-9495-3b1a54a33cba.png)


Another scene: Left and Right undistorted and rectified (stereo_before_refinement)
![image](https://user-images.githubusercontent.com/34694863/39412330-dd0321e2-4c5d-11e8-9821-7e4980445ac1.png)

I noticed looking at rviz that sptam publications are not smooth (as looking at raw), therefore each stereo frame is far from the previous one. I don't know if that is only visualization or if that sequence of frames is the one used for mapping.

I'm gonna collect mmore drives and test.

Tanks a lot for your advice!

**Comment by taihup** [comment]
Maybe S-PTAM is not running well. Depending on the configuration (features detector + descriptor, and other parameters), it will require a high computing power. Also, you can try to run the rosbag with a lower frame rate (rosbag play --clock --rate 0.5 rosbag_file.bag). What computer are you using? Check if the calibration is alright.

**Comment by breyner-posso** [comment]
Hi, how can I check if the calibration is alright? When I see the horizontal lines on both images they look well rectified (aligned) but I don't know if that is enough.
My computer has a Corei7 Vpro processor and 8GB of RAM.
Tks a lot for your advice!

**Comment by taihup** [comment]
The calibration looks fine, but could be wrong. Try to calibrate the camera with ROS calibration package.

You can change epipolardistance parameter to 2. It will triangulate more points.

Try to run s-ptam as nodelet instead of node. It is prepare for that. It will run much faster.

Disable Loop Closure module.
