### ISSUE TITLE
configurationfiles for local dataset

### ISSUE THREAD

**Issue by Rnandani** [lrse/sptam#3]
How to set .yaml configuration file for local dataset. I am using bubblebee2 of 640 x 480 pixels. 
For the beginner case, i took kitti.yaml as a configuration file for my local dataset also. But, it failed as it was not able to 'initialise the map'.

**Comment by taihup** [comment]
Are the cameras undistorted and rectified? check the launch file of level7.
There we run the stereo_image_proc node to undistort and rectify the images.
