### ISSUE TITLE
Gtest error while compilation

### ISSUE THREAD

**Issue by HainingLuo** [lrse/sptam#30]
Hi,

I encountered this error while compiling sptam:
![screenshot from 2018-05-17 10-03-56](https://user-images.githubusercontent.com/38414017/40152965-127e8578-59ba-11e8-914a-7433b7c13848.png)

I reinstalled gtest for a few times but failed to solve the issue.

Thanks in advance.

**Comment by taihup** [comment]
Check issue #12. You can find the same problem and the associated solution. However I summarised it here:

Uninstall completely gtest:
```
cd /usr/src/gtest/
sudo mkdir build
cd build
sudo cmake .. -DBUILD_SHARED_LIBS=ON
```

Remove devel and build directory inside catkin workspace in order to recompile from the scratch S-PTAM.

**Comment by HainingLuo** [comment]
Thank you soooooo much for your help. 

The project is fully compiled now. However, when I was running the KITTI and EuRoC datasets, I encountered another issue:
![screenshot from 2018-05-18 09-57-02](https://user-images.githubusercontent.com/38414017/40212441-6cb6e33c-5a82-11e8-8c34-194a8419c953.png)

I suppose this has nothing to do with the commands I used(since I was following your tutorial). For KITTI, I was using sequence 01 and it had been depressed, and for EuRoC, I chose V1_01_easy and had added sensor information as you suggested in README.

Thanks in advance.

**Comment by taihup** [comment]
The sequence 01 is one of the hardest in KITTI. So you must have a very strong computer to process all the frames. You also can tune some parameters to make it work better. Another posibility, if you don have a strong computer, you can play the dataset with a lower rate (rosbag play --clock --rate 0.5 dataset.bag). However, I suggest to try the system in other kitti sequence like 00. S-PTAM Vision only does not work properly in all the EuRoc sequences (and IMU is required to improve the performance, we have been doing some work to integrate the IMU but we do not have enough time to add all the documentation and support in the sort-term). Again, I suggest to test S-PTAM in the EuRoc MH01.sequence, that should works fine.

**Comment by HainingLuo** [comment]
Thanks a ton for help.

I tried to slow the replay of bagfile but didn't see any changes(possibly due to the poor computability of Jetson TX1 I was using). Then I transplanted the whole project to a much more powerful workstation. The compilation passed, very easily, but by the time I ran the KITTI sequence 00, I got this error:
![screenshot from 2018-05-19 15-41-12](https://user-images.githubusercontent.com/38414017/40266294-3db1adf2-5b7b-11e8-91d7-68ee50a71660.png)
And
![screenshot from 2018-05-19 15-41-42](https://user-images.githubusercontent.com/38414017/40266295-41a646fc-5b7b-11e8-9286-0652dca73ee4.png)
I thought maybe the package 'hector_pose_estimation' somehow corrupted, and I reinstalled it with 
` sudo apt-get install ros-kinetic-hector-pose-estimation`
and got
![screenshot from 2018-05-19 15-44-51](https://user-images.githubusercontent.com/38414017/40266313-97875b42-5b7b-11e8-8f0d-4448a3056fc8.png)

Do you have any idea what caused this?

Thanks in advance.

**Comment by taihup** [comment]
I think you have some problem linking with g2o library. Check [http://gdwarner.blogspot.com.ar/2009/03/c-runtime-symbol-lookup-error.html](http://gdwarner.blogspot.com.ar/2009/03/c-runtime-symbol-lookup-error.html) to understand the error. Tried to remove g2o and installed it again with all the dependencies. Install g2o with `checkinstall` command (it is musch better than make install) the Similar error was reported in #19.

**Comment by HainingLuo** [comment]
Hi, 
I reinstalled the g2o library following your instruction but unfortunately didn't see any difference. 
Thanks for help anyway.

**Comment by taihup** [comment]
Oh, just to be sure. Are you using the right g2o commit? remember that you need the to use the commit: `4b9c2f5b68d14ad479457b18c5a2a0bce1541a90`

```
git clone git@github.com:RainerKuemmerle/g2o.git
git checkout 4b9c2f5b68d14ad479457b18c5a2a0bce1541a90

```

**Comment by Gfuse** [comment]
I am installing sptam package on my OS: ubuntu 18.04, ROS Melodic. But I encounter the following error during compiling. 

I tried to Uninstall completely gtest, but the error still exits.
`cd /usr/src/gtest/ 
sudo mkdir build  
cd build  
sudo cmake .. -DBUILD_SHARED_LIBS=ON`
I also did it
`sudo apt install libgtest-dev build-essential cmake
cd /usr/src/googletest
sudo cmake .
sudo cmake --build . --target install`
I tried also to install opencv-4.0.1 and CUDA nvidia.
 
![Screenshot from 2019-03-11 02-16-23](https://user-images.githubusercontent.com/44868211/54104261-9762a500-43a5-11e9-9574-fa4a7805edac.png)

I will appreciate If you can help me. 
Thank you in advance

**Comment by taihup** [comment]
You have to remove the /usr/local/lib/libgtest.a static libraries. Also, remove the build and devel directories inside your catkin workspace. S-PTAM was not tested on 18.04 yet.

**Comment by Gfuse** [comment]
Thank you Taihup for your respond.

**Comment by taihup** [comment]
Did you make it work?

**Comment by Gfuse** [comment]
No, my supervisor decided to leave it for now. We will come back to it later.
