### ISSUE TITLE
ERROR: There is not any covisibility keyframes observing the tracked points

### ISSUE THREAD

**Issue by Dorothy-2016** [lrse/sptam#33]
Hi @taihup 
When I use my own camera to run sptam, the output is always like this:

[ WARN] [1529655500.726652359]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1529655500.767450854]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1529655500.806891177]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points

That is strange, and I cannot find any reason, could you help me to see how it happens, Thanks very much!

**Comment by taihup** [comment]
Hi Dorothy, which camera are you using? tell me the specs of the camera like resolution, frame-rate, baseline. Are cameras synchronised and are they global shutter? How do you calibrate the cameras?
Did you tried first with the datasets? Does S-PTAM work properly on the datasets? How many points are created in the initial map?

General possible issues that could be:
1) Wrong calibration.
2) Not enough features. Try to point the camera to a textured scene. Try to keep the camera still to be sure that fast movements are not making S-PTAM to fail.
3) CPU + RAM are not enough.

**Comment by Dorothy-2016** [comment]
**I use the mynt-camera:**
(1) camera info
----Left camera----
header: 
  seq: 326
  stamp: 
    secs: 1529658003
    nsecs: 436245362
  frame_id: "/mynt_left_frame"
height: 480
width: 752
distortion_model: "plumb_bob"
D: [-0.36255826702942184, 0.2040465812888242, 0.08530958495132553, 0.0, 0.0]
K: [373.2939628956764, 0.0, 382.36407395832225, 0.0, 383.2075525456734, 239.76864078299818, 0.0, 0.0, 1.0]
R: [0.9993493088776895, 0.006642334621333458, 0.03545191442591644, -0.006442587140966306, 0.9999627399462373, -0.005745588755299003, -0.0354887576087882, 0.005513448103700449, 0.9993548668883303]
P: [426.55486324894065, 0.0, 248.10321044921875, 0.0, 0.0, 426.55486324894065, 316.6848945617676, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---
----Right camera----
header: 
  seq: 265
  stamp: 
    secs: 1529658192
    nsecs: 379726116
  frame_id: "/mynt_right_frame"
height: 480
width: 752
distortion_model: "plumb_bob"
D: [-0.33425631730290767, 0.14150596847950164, 0.04458630550268736, 0.0, 0.0]
K: [373.2939628956764, 0.0, 381.42224864516413, 0.0, 383.2075525456734, 257.1245968166536, 0.0, 0.0, 1.0]
R: [0.9996958364987463, 0.013815658730326455, -0.020429441032955513, -0.01370040432888692, 0.9998894921168691, 0.005770829705925424, 0.02050691123248131, -0.0054891828277922735, 0.9997746423387553]
P: [426.55486324894065, 0.0, 248.10321044921875, -51.72445566683859, 0.0, 426.55486324894065, 316.6848945617676, 0.0, 0.0, 0.0, 1.0, 0.0]
binning_x: 0
binning_y: 0
roi: 
  x_offset: 0
  y_offset: 0
  height: 0
  width: 0
  do_rectify: False
---

----baseline:0.0121261
---- yes, the camera is synchronised and global shutter
---- I use the way in ros which you told me last time to calibrate the camera
----I tried the kitti_00.bag datasets, but it crashed after initialized with 70points, and I didn't open the Loop closure
---- my computer has GPU, but I don't know if I need to set something before using it or just run the code?
for the mynt camera, it was initialized with 10 points, and then give these errors

**Comment by taihup** [comment]
The camera baseline is wrong! It saying that the baseline is 1.2 cm!!!
Check the calibration.

**Comment by taihup** [comment]
at least the baseline number that you passed to me...

**Comment by Dorothy-2016** [comment]
sorry to reply you so late, because some other program I have no time to check this.
really really very thank you for your reply!
and yes, you are very right, why the baseline number is because I divided the original baseline by 10 at the last time and I forgot to correct it back. now the baseline is already right, and the result is also like before. what difference is that the initial step is finished normally (often with more features than before), So I record a bag file when I run the camera and sptam, maybe you can find it out that why it cannot work well. Very thanks again!
Here is the address of the bag file (I use the onedrive of microsoft because I failed to upload the bag file to google drive for some reason):
[https://1drv.ms/u/s!Aslti0q54tb-gmnmPUx9LFfT0Aql](url)
Hope your reply!

**Comment by Dorothy-2016** [comment]
well, about the address of the bag file, I tried to open it directly from here it cannot open and show 404, but when I copy this link to the website address blank of google browser it can be opened, so I'm not sure if you can open it successfully, if no, please let me know, I will find other ways to upload the data.

**Comment by taihup** [comment]
It looks like you bag is corrupt. I ran:
rosbag info mynttest.bag
output:
ERROR bag unindexed: mynttest.bag.  Run rosbag reindex.

After rosbag reindex the rosbag works. I need the rosbag only with the
basic information (raw camera images, camera_info messages). Also, provide
me your customise .launch file that you are using to run S-PTAM.
