### ISSUE TITLE
Building standalone

### ISSUE THREAD

**Issue by fawadahm** [lrse/sptam#34]
Hi,

Thank you for open-sourcing your code. I am trying to build S-PTAM on Ubuntu 16.04 without ROS. I've installed all the dependencies and tried to build **standalone** using the instructions given in the readme. However, to do so, we need to build **sptam** as given in the CMakeLists.txt as:

`_target_link_libraries(sptam-stereo sptam frameGenerator ${X11_LIBRARIES} boost_program_options ${THREAD_LIBS})_`

When I try to build **sptam**, after I run make, I get the following output. Can you please tell me how to go about this? Specifically, will I need to run ROS or can I get the standalone version running without ROS?

`Scanning dependencies of target test_set_union
Scanning dependencies of target frameGenerator
Scanning dependencies of target test_CovisibilityGraph
[  2%] Building CXX object src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/test_set_union.cpp.o
[  4%] Building CXX object src/standAlone/CMakeFiles/frameGenerator.dir/FrameGenerator/FileSequenceFrameGenerator.cpp.o
[  8%] Building CXX object src/standAlone/CMakeFiles/frameGenerator.dir/FrameGenerator/VideoFileFrameGenerator.cpp.o
[  8%] Building CXX object src/standAlone/CMakeFiles/frameGenerator.dir/FrameGenerator/ListOfFilesFrameGenerator.cpp.o
[ 12%] Building CXX object src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/test_CovisibilityGraph.cpp.o
[ 12%] Building CXX object src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/__/__/__/sptam/utils/CovisibilityGraph.cpp.o
[ 14%] Building CXX object src/sptam/CMakeFiles/sptam.dir/MotionModel.cpp.o
[ 16%] Building CXX object src/sptam/CMakeFiles/sptam.dir/CameraPose.cpp.o
[ 18%] Building CXX object src/sptam/CMakeFiles/sptam.dir/Frame.cpp.o
[ 20%] Building CXX object src/sptam/CMakeFiles/sptam.dir/FeatureExtractorThread.cpp.o
[ 22%] Linking CXX static library libframeGenerator.a
[ 24%] Linking CXX executable test_set_union
[ 24%] Built target frameGenerator
[ 26%] Building CXX object src/sptam/CMakeFiles/sptam.dir/g2o_driver.cpp.o
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x3a): undefined reference to `pthread_key_delete'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x3a): undefined reference to `pthread_key_delete'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x27): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x8b): undefined reference to `pthread_setspecific'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::CreateKey()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE9CreateKeyEv[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE9CreateKeyEv]+0x25): undefined reference to `pthread_key_create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::CreateKey()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE9CreateKeyEv[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE9CreateKeyEv]+0x25): undefined reference to `pthread_key_create'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::GetOrCreateValue() const':
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x89): undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/build.make:94: recipe for target 'src/tests/sptam/utils/set_union/test_set_union' failed
make[2]: *** [src/tests/sptam/utils/set_union/test_set_union] Error 1
CMakeFiles/Makefile2:197: recipe for target 'src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/all' failed
make[1]: *** [src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object src/sptam/CMakeFiles/sptam.dir/BundleDriver.cpp.o
[ 30%] Building CXX object src/sptam/CMakeFiles/sptam.dir/sptam.cpp.o
[ 32%] Building CXX object src/sptam/CMakeFiles/sptam.dir/RowMatcher.cpp.o
[ 34%] Linking CXX executable test_CovisibilityGraph
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/build.make:121: recipe for target 'src/tests/sptam/CovisibilityGraph/test_CovisibilityGraph' failed
make[2]: *** [src/tests/sptam/CovisibilityGraph/test_CovisibilityGraph] Error 1
CMakeFiles/Makefile2:252: recipe for target 'src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/all' failed
make[1]: *** [src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/all] Error 2
[ 36%] Building CXX object src/sptam/CMakeFiles/sptam.dir/MapMakerThread.cpp.o
[ 38%] Building CXX object src/sptam/CMakeFiles/sptam.dir/tracker_g2o.cpp.o
[ 40%] Building CXX object src/sptam/CMakeFiles/sptam.dir/MapMaker.cpp.o
[ 42%] Building CXX object src/sptam/CMakeFiles/sptam.dir/match_to_points.cpp.o
[ 44%] Building CXX object src/sptam/CMakeFiles/sptam.dir/types_sba_extension.cpp.o
[ 46%] Building CXX object src/sptam/CMakeFiles/sptam.dir/Measurement.cpp.o
[ 48%] Building CXX object src/sptam/CMakeFiles/sptam.dir/Camera.cpp.o
[ 50%] Building CXX object src/sptam/CMakeFiles/sptam.dir/FrustumCulling.cpp.o
[ 52%] Building CXX object src/sptam/CMakeFiles/sptam.dir/TrackerViewStereo.cpp.o
[ 54%] Building CXX object src/sptam/CMakeFiles/sptam.dir/StereoGraph.cpp.o
[ 56%] Building CXX object src/sptam/CMakeFiles/sptam.dir/StereoFrame.cpp.o
[ 58%] Building CXX object src/sptam/CMakeFiles/sptam.dir/MapPoint.cpp.o
[ 60%] Building CXX object src/sptam/CMakeFiles/sptam.dir/ImageFeatures.cpp.o
[ 62%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/projection_derivatives.cpp.o
[ 64%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/timer.cpp.o
[ 66%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/CovisibilityGraph.cpp.o
[ 68%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/pose_covariance.cpp.o
[ 70%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/draw/Draw.cpp.o
[ 72%] Building CXX object src/sptam/CMakeFiles/sptam.dir/utils/log/Logger.cpp.o
[ 74%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/LoopClosing.cpp.o
[ 76%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/SmoothEstimatePropagator.cpp.o
[ 78%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/StereoMatcher.cpp.o
[ 80%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/PoseEstimator.cpp.o
[ 82%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o
[ 84%] Building CXX object src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/FBRISK.cpp.o
[ 86%] Linking CXX shared library libsptam.so
[ 88%] Built target sptam
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by taihup** [comment]
Hi @fawadahm, please post how did you solve the issue, so it can helps to others. Thanks!

**Comment by fawadahm** [comment]
Yes sure.

To fix this, I cleaned the project, both **sptam** and **standalone**. After that, I build **sptam** and then **standalone**. That seemed to fix the problem.
