### ISSUE TITLE
Running KITTI sequences on standalone

### ISSUE THREAD

**Issue by fawadahm** [lrse/sptam#35]
Hi,

I am trying to run the **standalone** version of S-PTAM on an Ubuntu 16.04. I followed the directions given in the README.md to build sptam and then run the standalone file. However, I encounter a segmentation fault on the second frame of the KITTI odometery sequences (00-02). The following is the output from the program

detector: GFTT
  nfeatures: 1000
  qualityLevel: 0.010000
  minDistance: 15.000000
  blockSize: 3
  useHarrisDetector: 0
  k: 0.040000
detector: GFTT
  nfeatures: 1000
  qualityLevel: 0.010000
  minDistance: 15.000000
  blockSize: 3
  useHarrisDetector: 0
  k: 0.040000
descriptor: BRIEF
  bytes: 32
  use_orientation: 0
descriptor: BRIEF
  bytes: 32
  use_orientation: 0
matcher: BruteForce-Hamming
OpenCV: threads set to -1
Parsing timestamps file /media/fawad/DATA/Kitti_dataset/sequences/00/times.txt
Loaded 4541 timestamps poses
WARNING tracking is slower than the camera feed by 0.398667 (s)
Segmentation fault (core dumped)

The function call graph that explains the crash better is as follows:

`main -> SptamWrapper::Add -> SPTAM::track -> tracker_g2o::RefineCameraPose -> G2ODriver::AddVertex g2o_driver.cpp:125`

Has anyone encountered this problem before? I look into it and it seems like **sptam** has some problems with its g2o library which causes the segmentation fault. I'll highly appreciate any help in this regard.

**Comment by taihup** [comment]
Did you try to run the ROS version? The bug could be related with the vectorization of Eigen. You can try to run S-PTAM in Debug mode, Moreover, to have more information you can compile g2o in Debug mode too.
Just to be sure, are you using the g2o version required by S-PTAM right?

**Comment by fawadahm** [comment]
Thank you! I changed the version of g2o to the commit you mentioned in the README.md. That fixed the problem with the g2o library. However, there is a new problem now and the call graph for it as is follows;

main -> SptamWrapper::Add () -> MotionModel::predictPose ()

In motion model predict pose, the fault occurs at 
`predictedOrientation = orientation_;`

And this happens when SPTAM is reading the first frame. Please let me know what other information I can provide to help pin down the problem.

**Comment by taihup** [comment]
Check that all the paths used as input are right. Try to run the ROS version, and check if a similar error appear. Please paste here the value of the variables that are related to the crash (e.g. orientation_), maybe could help us to find the bug. Finally, you can try to run in Debug mode and go step by step. This should give us more information about what is going on.
