### ISSUE TITLE
Error Running kitti.launch with kitti_01.bag

### ISSUE THREAD

**Issue by WwYyFan** [lrse/sptam#36]
... logging to /home/efun/.ros/log/d04e5df8-a5a5-11e8-98a3-4cedfbcaaae4/roslaunch-efun-26211.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:35003/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/efun/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[start_broadcaster-1]: started with pid [26228]
process[sptam_path-2]: started with pid [26235]
process[sptam-3]: started with pid [26248]
[ INFO] [1534899226.980898860]: Initializing nodelet with 12 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1534899227.117075503]: S-PTAM stereo node initialized.
[ INFO] [1534899227.308119776, 1385798597.275167144]: init calib
[ INFO] [1534899227.308562666, 1385798597.275167144]: baseline: 0.537166
[ INFO] [1534899227.352500830, 1385798597.325656805]: Trying to intialize map...
[ INFO] [1534899227.362344444, 1385798597.335742839]: Map initialized with 61 points.
[ WARN] [1534899227.448437967, 1385798597.416596004]: Not enough points for tracking.
[ WARN] [1534899227.549903210, 1385798597.518844700]: Not enough points for tracking.
[ WARN] [1534899227.652603786, 1385798597.619818541]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899227.757493059, 1385798597.730895827]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899227.861465985, 1385798597.832033463]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899227.963549905, 1385798597.933671664]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.043840863, 1385798598.014559739]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.172265201, 1385798598.146099253]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.274452372, 1385798598.247198987]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.378589889, 1385798598.348147057]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.480684566, 1385798598.449195250]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.588424055, 1385798598.560424138]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.690725644, 1385798598.661514474]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.794051950, 1385798598.763016618]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899228.899101231, 1385798598.874177932]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.003824312, 1385798598.975271649]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.082420023, 1385798599.056040514]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.180803979, 1385798599.157483901]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.314867772, 1385798599.289054709]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.392381368, 1385798599.359861763]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.496572188, 1385798599.470865327]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.625864561, 1385798599.602596593]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.729981015, 1385798599.703611855]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.807452677, 1385798599.774369327]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899229.939548645, 1385798599.915924993]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899230.041654707, 1385798600.017228531]: Not enough points for tracking.
ERROR: There is not any covisibility keyframes observing the tracked points
[ WARN] [1534899230.142771535, 1385798600.118318340]: Not enough points for tracking.

**Comment by WwYyFan** [comment]
Has anyone encountered this problem?Please tell me how to slove it.

**Comment by taihup** [comment]
Hi WwYyFan, the KITTI sequence 01 is a little complicated for the Visual SLAM systems. What computer are you using? you can try to play the rosbag slower in case your computer does not have enough power.  Try using rosbag play --clock --rate 0.2 <KITTI_SEQUENCE>.bag

**Comment by WwYyFan** [comment]
@taihup Hi , I have tried to  play the rosbag slower. and Still get the same error message.

My computer configuration:
OS: ubuntu 16.04
Memory: 16G
Processor:Intel® Core™ i7-8700 CPU @ 3.20GHz × 12 
Graphics:GeForce GTX 1060 5GB/PCIe/SSE2

**Comment by taihup** [comment]
Your computer is fine, so it is not the issue. Did you try with another sequence or another dataset? try with the KITTI 00 sequence.

**Comment by WwYyFan** [comment]
Sorry to reply late!
I have tried the KITTI_00.bag.the S-PTAM hangs on " Map initialized with 98 points." 


... logging to /home/efun/.ros/log/00998e94-a996-11e8-b414-4cedfbcaaae4/roslaunch-efun-32034.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:44761/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/efun/catkin...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[start_broadcaster-1]: started with pid [32051]
process[sptam_path-2]: started with pid [32058]
process[sptam-3]: started with pid [32071]
[ INFO] [1535332817.387241574]: Initializing nodelet with 12 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1535332817.521614903]: S-PTAM stereo node initialized.
[ INFO] [1535332818.142127657, 1385798153.551644865]: init calib
[ INFO] [1535332818.142507240, 1385798153.551644865]: baseline: 0.537166
[ INFO] [1535332818.187667427, 1385798153.559729108]: Trying to intialize map...
[ INFO] [1535332818.205650456, 1385798153.563764119]: Map initialized with 98 points.

**Comment by taihup** [comment]
Once S-PTAM shows " Map initialized with 98 points.", try to visualise the
trajectory and the reconstructed map with rviz. You also can do *rostopic
list*, and check which topics are published.

**Comment by WwYyFan** [comment]
@taihup Hi , I have tried to add Map and Trajectory in rviz. Map has no topics to choose，Trajectory show error. 
![2018-08-29 15-23-24](https://user-images.githubusercontent.com/21033648/44774591-129d0000-aba6-11e8-8eeb-681893df9d41.png)

**Comment by taihup** [comment]
You are setting th wrong values to visualise the output of S-PTAM. First, paste here the output of the command `rostopic list` when you are running S-PTAM (after: Map initialized with 98 points.)

The to visualise S-PTAM output you must set in rviz:
1) Fixed Frame as `map`
2) Add -> By Topic -> PointCloud
3) Add -> By Topic -> Path

That should work... maybe you have to tune the visualisation configuration for the trajectory and the map.

**Comment by WwYyFan** [comment]
@taihup thanks a lot！！
![2018-08-29 19-11-43](https://user-images.githubusercontent.com/21033648/44824613-22b1ef80-ac39-11e8-8924-3938f7849f47.png)

**Comment by taihup** [comment]
No worries :)

**Comment by WwYyFan** [comment]
Another question is why Kitti_01.bag output "Not enough points for tracking" , I also encountered this problem when I running with my own stereo camera.

**Comment by taihup** [comment]
It should work :S You can try some things. How did you generate the rosbag? Did you use the right calibration file (remember that there three different calibration files)? Have you uncompressed the rosbag?

Then you must try the standalone version of S-PTAM with sequence 01. If it does not work in the standalone it will not work in the ROS version.

If S-PTAM still gets lost then, try to change some configuration parameters. For example you can increase the parameter a little bit as `MatchingNeighborhood` and/or `MatchingDistance`. Try also to increase the parameter `FrustumFarPlaneDist` to several KM as 10000.0. Finally you can try to make more flexible the keyframe creation strategy decrerasing the `minimumTrackedPointsRatio` value.

**Comment by WwYyFan** [comment]
@taihup  Thanks a lot, It's work with my own stereo camera now,But when I slightly speed up moving my camera , the error message output again.

**Comment by taihup** [comment]
All the advices that I gave to you were to make S-PTAM works in the KITTI 01 sequence. For your own camera, you should use the ROS version only. Also It is very probably that your camera does not have a good calibration. So try to calibrate it again using the [http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration](http://wiki.ros.org/camera_calibration/Tutorials/StereoCalibration). Once the camera is properly calibrated, and if the system does not work properly, you can change the value of the EpipolarDistance parameter to 1.0, 2.0 or 4.0, if the calibration between the camera is not so good.
Check the issues #16 #27 #24 #10 #7, maybe they can be useful for you.

Some few questions:
What camera are you using? Are the cameras synchronised? Do the cameras have global-shutter?

**Comment by WwYyFan** [comment]
I'm using mynteye camera,it's synchronised,has global-shutter.
And I found that the topic "/sptam/right_frame_after_refine“ has no image.

**Comment by taihup** [comment]
To publish in `/sptam/right_frame_after_refine` topic, you should compile S-PTAM with the cmake flag `-DSHOW_TRACKED_FRAMES=ON`

I have never tried the MYNTEYE camera but it should work. It looks like it is a calibratino issue. Have you calibrated the camera? How? Try with the ROS calibration package that I recommend you.

**Comment by WwYyFan** [comment]
Yes，MYNTEYE baseline : 12cm , and sptam output baseline 0.19
but I calibrated using the program that comes with the camera , no use  ROS calibration package.

**Comment by taihup** [comment]
That means that the calibration is wrong, try using the ROS calibration package that I mentioned to you.

**Comment by WwYyFan** [comment]
I just calibrated using the program that comes with the camera again.and sptam ouput baseline 0.12 now.it's ok?  and the Map  often initialized with 20~30  points.Do you have any suggestions to increase the number of points? Could you send me the some samples of the images processed by S-PTAM?

**Comment by taihup** [comment]
Are you rectifying the images, right? You must do it with the ROS package [http://wiki.ros.org/stereo_image_proc?distro=diamondback](http://wiki.ros.org/stereo_image_proc?distro=diamondback). Check the EuRoc launch  to check how to use it.
