### ISSUE TITLE
symbol lookup error: /home/ros/vslam/devel/lib/libsptam.so: undefined symbol

### ISSUE THREAD

**Issue by ChenSXing** [lrse/sptam#37]
ros@ros-ubuntu:~/vslam$ roslaunch sptam kitti.launch 
... logging to /home/ros/.ros/log/7615fe52-b75e-11e8-a10e-002324de281e/roslaunch-ros-ubuntu-13670.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.100.124:46473/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/ros/vslam/s...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: camera_gray_left
 * /sptam/camera_frame: camera_gray_left
 * /sptam/map_frame: map
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/prediction_frame: odom
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: camera_gray_left
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://192.168.100.124:11311

process[start_broadcaster-1]: started with pid [13688]
process[sptam_path-2]: started with pid [13689]
process[sptam-3]: started with pid [13704]
[ INFO] [1536855684.505911059]: Initializing nodelet with 4 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1536855684.572702099]: Loop Detector initializing, loading vocabulary
[ INFO] [1536855691.775018863, 1317013705.076373054]: S-PTAM stereo node initialized.
[ INFO] [1536855703.159725135, 1317013706.214797726]: init calib
[ INFO] [1536855703.160009472, 1317013706.214797726]: baseline: 0.537151
[ INFO] [1536855703.180599290, 1317013706.216826523]: Trying to intialize map...
[ INFO] [1536855703.196421446, 1317013706.218838018]: Map initialized with 111 points.
/home/ros/vslam/devel/lib/sptam/sptam_node: symbol lookup error: /home/ros/vslam/devel/lib/libsptam.so: undefined symbol: _ZN3g2o30OptimizationAlgorithmLevenbergC1ESt10unique_ptrINS_6SolverESt14default_deleteIS2_EE
[sptam-3] process has died [pid 13704, exit code 127, cmd /home/ros/vslam/devel/lib/sptam/sptam_node /stereo/left/image_rect:=/kitti/camera_gray_left/image_raw /stereo/right/image_rect:=/kitti/camera_gray_right/image_raw /stereo/left/camera_info:=/kitti/camera_gray_left/camera_info /stereo/right/camera_info:=/kitti/camera_gray_right/camera_info __name:=sptam __log:=/home/ros/.ros/log/7615fe52-b75e-11e8-a10e-002324de281e/sptam-3.log].
log file: /home/ros/.ros/log/7615fe52-b75e-11e8-a10e-002324de281e/sptam-3*.log
^C[sptam_path-2] killing on exit
[start_broadcaster-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by ChenSXing** [comment]
I run the kitti data,but I always get this error!!

**Comment by taihup** [comment]
Hi @ChenSXing It looks like you are having issues with g2o. Are you using the g2o version mentioned in the installation instructions? Check the issues #34 #22 and #13.
