### ISSUE TITLE
Improvement for pure localization after running a SLAM session

### ISSUE THREAD

**Issue by salahkhan94** [lrse/sptam#38]
Hi @taihup , 
I'm planning on using SPTAM for my personal project, after a SLAM session I'd like to be able to store the optimized 3D feature Pointcloud map and be able to load it and use it for pure Localization later. 
Could you give me pointers as to where I could start?

**Comment by taihup** [comment]
It is hard to say, I think you have to save the whole map (keyframes, points and relations between them). Then, you can use the DBoW2 to relocalise the current camera with respect to the leyframes stored. You should use the feature extracted in the keyframe to do the relocalisation. Once you relocalise the current camera,  you can start tracking the local map of the keyframe.

**Comment by salahkhan94** [comment]
Thanks, I'll post here if I have any more queries in the future or if I make some progress.

**Comment by taihup** [comment]
Ok, I leave it open
