### ISSUE TITLE
 error: ‘DBoW2::FBrief::TDescriptor {aka class std::bitset<256ul>}’ has no member named ‘resize’

### ISSUE THREAD

**Issue by VictorySpecificationII** [lrse/sptam#39]
Thanks for making your code open-source!

I managed to install all the packages needed, and after running either

catkin_make --pkg sptam -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSINGLE_THREAD=OFF -DSHOW_TRACKED_FRAMES=ON -DSHOW_PROFILING=ON -DPARALLELIZE=ON

or

catkin_make --pkg sptam -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_LOOPCLOSURE=ON -DSINGLE_THREAD=OFF -DSHOW_TRACKED_FRAMES=ON -DSHOW_PROFILING=ON -DPARALLELIZE=ON

in the README file i am greeted with this message:

Running ROS Kinetic on Ubuntu 16.04. I will continue poking and prodding around to find a way around this and will post a solution if successful, but in the meantime any guidance is very much helpful and appreciated. Thank you!

####
####
[  2%] Linking CXX executable test_set_union
[  4%] Linking CXX executable test_CovisibilityGraph
[ 14%] Built target sptam_ros
/usr/bin/ld: /usr/lib/libgtest.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
sptam/src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/build.make:123: recipe for target 'sptam/src/tests/sptam/CovisibilityGraph/test_CovisibilityGraph' failed
make[2]: *** [sptam/src/tests/sptam/CovisibilityGraph/test_CovisibilityGraph] Error 1
CMakeFiles/Makefile2:3242: recipe for target 'sptam/src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/all' failed
make[1]: *** [sptam/src/tests/sptam/CovisibilityGraph/CMakeFiles/test_CovisibilityGraph.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED2Ev[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEED5Ev]+0x3a): undefined reference to `pthread_key_delete'
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::~ThreadLocal()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED2Ev[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEED5Ev]+0x3a): undefined reference to `pthread_key_delete'
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::GetOrCreateValue() const':
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x27): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE16GetOrCreateValueEv]+0x8b): undefined reference to `pthread_setspecific'
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::CreateKey()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE9CreateKeyEv[_ZN7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE9CreateKeyEv]+0x25): undefined reference to `pthread_key_create'
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<std::vector<testing::internal::TraceInfo, std::allocator<testing::internal::TraceInfo> > >::CreateKey()':
gtest-all.cc:(.text._ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE9CreateKeyEv[_ZN7testing8internal11ThreadLocalISt6vectorINS0_9TraceInfoESaIS3_EEE9CreateKeyEv]+0x25): undefined reference to `pthread_key_create'
/usr/lib/libgtest.a(gtest-all.cc.o): In function `testing::internal::ThreadLocal<testing::TestPartResultReporterInterface*>::GetOrCreateValue() const':
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x25): undefined reference to `pthread_getspecific'
gtest-all.cc:(.text._ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv[_ZNK7testing8internal11ThreadLocalIPNS_31TestPartResultReporterInterfaceEE16GetOrCreateValueEv]+0x89): undefined reference to `pthread_setspecific'
collect2: error: ld returned 1 exit status
sptam/src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/build.make:96: recipe for target 'sptam/src/tests/sptam/utils/set_union/test_set_union' failed
make[2]: *** [sptam/src/tests/sptam/utils/set_union/test_set_union] Error 1
CMakeFiles/Makefile2:3187: recipe for target 'sptam/src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/all' failed
make[1]: *** [sptam/src/tests/sptam/utils/set_union/CMakeFiles/test_set_union.dir/all] Error 2
[ 16%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o
/home/antreas/FYP/catkin_fyp_ws/src/sptam/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp: In member function ‘DetectionMatch DLDLoopDetector<F>::detectloop(const SharedKeyFrame&) [with F = DBoW2::FBrief; sptam::Map::SharedKeyFrame = std::shared_ptr<CovisibilityGraph<StereoFrame, MapPoint, Measurement>::KeyFrame>]’:
/home/antreas/FYP/catkin_fyp_ws/src/sptam/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp:99:15: error: ‘DBoW2::FBrief::TDescriptor {aka class std::bitset<256ul>}’ has no member named ‘resize’
     bset_desc.resize(char_bset_desc.size());
               ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-int-in-bool-context’
sptam/src/sptam/CMakeFiles/sptam.dir/build.make:854: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o' failed
make[2]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o] Error 1
CMakeFiles/Makefile2:3075: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/all' failed
make[1]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

**Comment by taihup** [comment]
Hi @VictorySpecificationII, it looks like you have an issue with libgtest library. Please check the issues #34 #12.

**Comment by VictorySpecificationII** [comment]
Hello, 

Sorry it took me this long to give an update.

Following snippets from issues 34, 30 and 12 i managed to get rid of the gtest error. Turns out, 

sudo apt-get install --reinstall libgtest-dev
cd /usr/src/gtest
sudo mkdir build
cd build
sudo cmake .. -DBUILD_SHARED_LIBS=ON

then copying the libgtest.so and libgtest_main.so into /usr/lib is the trick to that. Nothing new.

I deleted the build and devel folders and recompiled it again, I dont' remember which issue ticket it was but it was recommended.

Now my problem lies in compiling with loop closure capabilities. It will compile with the LOOPCLOSURE flag set to OFF but as soon as I try compiling it with that flag ON it gives me this:

Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o
/home/antreas/FYP/catkin_fyp_ws/src/sptam/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp: In member function ‘DetectionMatch DLDLoopDetector::detectloop(const SharedKeyFrame&) [with F = DBoW2::FBrief; sptam::Map::SharedKeyFrame = std::shared_ptr<CovisibilityGraph<StereoFrame, MapPoint, Measurement>::KeyFrame>]’:
/home/antreas/FYP/catkin_fyp_ws/src/sptam/src/sptam/loopclosing/detectors/DLDLoopDetector.cpp:99:15: error: ‘DBoW2::FBrief::TDescriptor {aka class std::bitset<256ul>}’ has no member named ‘resize’
bset_desc.resize(char_bset_desc.size());
^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-int-in-bool-context’
sptam/src/sptam/CMakeFiles/sptam.dir/build.make:854: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o' failed
make[2]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/loopclosing/detectors/DLDLoopDetector.cpp.o] Error 1
CMakeFiles/Makefile2:3075: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/all' failed
make[1]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed

GTest is seemingly working, am I missing something?

Thank you

**Comment by taihup** [comment]
It looks like your issue now is related with DBoW2 library. Try to completely remove it, and clean your work space (remove build and devel directories inside catkin work space). Then, make a clean installation of DBoW2 and try to compile again S-PTAM. Furthermore, If it does not work paste here the compilation output of DBoW2.

**Comment by VictorySpecificationII** [comment]
I will try it out and report back, thanks for the reply.

It may be a stupid question but, do the libraries ros-utils and the rest of the dependencies go into the catkin workspace? because currently I have them in a folder outside the catkin workspace.

**Comment by taihup** [comment]
Only ROS packages (ros-utils for example) should go inside catkin_ws/src/ directory. The non-ROS libraries could be outside.

**Comment by VictorySpecificationII** [comment]
Hello,

For now I'll forego the loop closure capabilities as my supervisor wants me to finish this project on time. Thank you for your help, once my project is done I will re-install SPTAM on a fresh VM, and the help you've given me so far has proved effective.
