### ISSUE TITLE
rviz default configuration

### ISSUE THREAD

**Issue by weiweikong** [lrse/sptam#4]
I do not have so much experience in rviz with SLAM, so would it be possible to share the rviz configuration with different datasets? I tried several parameters with the cloud, but it looks very different comparing with the video on your Youtube site.

**Comment by taihup** [comment]
Hi WeiWie, The KITTI video comes from an old version of S-PTAM. However, you can reproduce a similar behavior. The MIT video is from this current version, so your results must be really similar to the youtube video. You always can save the rviz parameters (camera view, point cloud size, etc) when you quit from rviz, so yes, you can share the visual aspects of rviz for all datasets.
