### ISSUE TITLE
KITTI Bag Files

### ISSUE THREAD

**Issue by hlezki** [lrse/sptam#44]
Hi,

I can not download kitti rosbag files that you provide its link in the Readme.md (fs01.cifasis-conicet.gov.ar:90/~pire/datasets/KITTI/bags/).
Is it possible to provide a new way to download it?
Thank you.

**Comment by hlezki** [comment]
Hello,
Can you please share kitti rosbag files again. I could not download it. I think the link is broken. I tried to use 2 different converter in order to convert synhronized Kitti images into rosbag files with the following algorithms

    https://github.com/lrse/dataset2bag
    https://github.com/ethz-asl/kitti_to_rosbag

I created this rosbags to pulish following topics;
/kitti_stereo/left/image_rect
/kitti_stereo/right/image_rect
/kitti_stereo/left/camera_info
/kitti_stereo/right/camera_info

However, SPTAM algorithm stucked into "S-PTAM stereo node initialized". It does not continue processing. I also checked log file, it does not contain any pose information such as refined camera pose. On the other hand, for Euroc dataset i can run the code and i can reach the pose informations. So, the problem is related with the kitti bag files and/or kitti launch file.
Please can you share your kitti rosbag files again, the link is broken.
Thank you

**Comment by taihup** [comment]
the KITTI sequence is available now.

The topics looks fine. I don't see anything wrong with the topic, try to visualise them to check if they are ok, you can use `rostopic echo <topic-name>`

**Comment by ghost** [comment]
Cannot download the rosbag files for KITTI sequence 02, 03, 05, 07-10. 
Keep getting Forbidden error: You don't have permission to access /~pire/datasets/KITTI/bags/kitti_07.bag on this server.

**Comment by taihup** [comment]
@shubhendu1907 fixed it.
