### ISSUE TITLE
rosplay kitti_04 error,need help

### ISSUE THREAD

**Issue by aiyanxiao** [lrse/sptam#48]
roslaunch sptam kitti.launch
... logging to /home/cvg/.ros/log/4323bc3c-e44d-11ea-a471-84ef18a6a32e/roslaunch-cvg-L-8280.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cvg-L:35826/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /sptam/BundleAdjustmentActiveKeyframes: 10
 * /sptam/DescriptorExtractor/Name: BRIEF
 * /sptam/DescriptorExtractor/bytes: 32
 * /sptam/DescriptorMatcher/Name: BruteForce-Hamming
 * /sptam/DescriptorMatcher/crossCheck: False
 * /sptam/EpipolarDistance: 0
 * /sptam/FeatureDetector/Name: GFTT
 * /sptam/FeatureDetector/minDistance: 15.0
 * /sptam/FeatureDetector/nfeatures: 1000
 * /sptam/FeatureDetector/qualityLevel: 0.01
 * /sptam/FeatureDetector/useHarrisDetector: False
 * /sptam/FrustumFarPlaneDist: 10000.0
 * /sptam/FrustumNearPlaneDist: 0.1
 * /sptam/LoopDetectorVocabulary: /home/cvg/catkin_...
 * /sptam/MatchingCellSize: 15
 * /sptam/MatchingDistance: 25
 * /sptam/MatchingNeighborhood: 2
 * /sptam/approximate_sync: False
 * /sptam/base_frame: left_camera
 * /sptam/camera_frame: left_camera
 * /sptam/minimumTrackedPointsRatio: 0.9
 * /sptam/publish_on_fail: True
 * /sptam/publish_transform: True
 * /sptam/reference_frame: left_camera
 * /sptam/use_prediction: False
 * /use_sim_time: True

NODES
  /
    sptam (sptam/sptam_node)
    sptam_path (ros_utils/pose_to_path)
    start_broadcaster (tf2_ros/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[start_broadcaster-1]: started with pid [8297]
process[sptam_path-2]: started with pid [8298]
process[sptam-3]: started with pid [8306]
[ INFO] [1598083334.440576321]: Initializing nodelet with 8 worker threads.
  crossCheck: 0
OpenCV: threads set to -1
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  nfeatures: 1000
  qualityLevel: 0.01
  minDistance: 15
  blockSize: 3
  useHarrisDetector: 0
  k: 0.04
  bytes: 32
  use_orientation: 0
  bytes: 32
  use_orientation: 0
[ INFO] [1598083334.617317674]: S-PTAM stereo node initialized.
[ INFO] [1598083342.286254159, 1385799339.561438617]: init calib
[ INFO] [1598083342.286648398, 1385799339.561438617]: baseline: 0.537151
[ INFO] [1598083342.325401229, 1385799339.565474172]: Trying to intialize map...
[ INFO] [1598083342.346033684, 1385799339.567491247]: Map initialized with 137 points.
[sptam-3] process has died [pid 8306, exit code -11, cmd /home/cvg/catkin_ws/devel/lib/sptam/sptam_node /stereo/left/image_rect:=/kitti_stereo/left/image_rect /stereo/right/image_rect:=/kitti_stereo/right/image_rect /stereo/left/camera_info:=/kitti_stereo/left/camera_info /stereo/right/camera_info:=/kitti_stereo/right/camera_info __name:=sptam __log:=/home/cvg/.ros/log/4323bc3c-e44d-11ea-a471-84ef18a6a32e/sptam-3.log].
log file: /home/cvg/.ros/log/4323bc3c-e44d-11ea-a471-84ef18a6a32e/sptam-3*.log

I meet this problem ,  I am a new for ROS, could you help me with this problem, please?

**Comment by taihup** [comment]
Hi, sorry for the late reply. Some questions for you: Are you working on Ubuntu 16.04? Which eigen version are you using? Have you try to use standalone version disabling Loop-Closure?

**Comment by aiyanxiao** [comment]
> Hi, sorry for the late reply. Some questions for you: Are you working on Ubuntu 16.04? Which eigen version are you using? Have you try to use standalone version disabling Loop-Closure?

Thanks for your reply! Yes, it is. The eigen is 3.3.7. I have try to use standalone version disabling Loop-Closure, but it is still not done. What could I do to solve this problem, please?

**Comment by taihup** [comment]
This issue is related: #47 , copying here a comment that could be useful

Currently, there is a known bug related memory linearization related to eigen. The workaround is to use the eigen version 3.2.10. You should remove any other eigen installed and recompile all the S-PTAM dependencies with the 3.2.10 (opencv, g2o, etc).

Give it a shot and let me know.
