### ISSUE TITLE
Please HELP me::::::when-->“catkin_make --pkg sptam -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSINGLE_THREAD=OFF -DSHOW_TRACKED_FRAMES=ON -DSHOW_PROFILING=ON -DPARALLELIZE=ON”

### ISSUE THREAD

**Issue by sunhm415** [lrse/sptam#49]
Every Step ！I have fixed all the err or bug before   “catkin_make.......”

I recieve the ERR (it seems like very EZ about grammer !!),,when I run "sudo "catkin_make --pkg sptam -DCMAKE_BUILD_TYPE=RelWithDebInfo -DSINGLE_THREAD=OFF -DSHOW_TRACKED_FRAMES=ON -DSHOW_PROFILING=ON -DPARALLELIZE=ON" 

ERR : 
[ 34%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/RowMatcher.cpp.o
[ 36%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/StereoFrame.cpp.o
Scanning dependencies of target sptam_ros
[ 38%] Building CXX object sptam/src/ros/CMakeFiles/sptam_ros.dir/stereo_driver.cpp.o
[ 40%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/StereoGraph.cpp.o
[ 42%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/TrackerViewStereo.cpp.o
[ 44%] Building CXX object sptam/src/sptam/CMakeFiles/sptam.dir/g2o_driver.cpp.o
[ 46%] Building CXX object sptam/src/ros/CMakeFiles/sptam_ros.dir/base_driver.cpp.o
In file included from /home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:3:0:
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:43:84: error: ‘VertexSBAPointXYZ’ was not declared in this scope
 class G2O_TYPES_SBA_API EdgeProjectP2MCRight : public  BaseBinaryEdge<2, Vector2d, VertexSBAPointXYZ, VertexCam>
                                                                                    ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:43:112: error: template argument 3 is invalid
 class G2O_TYPES_SBA_API EdgeProjectP2MCRight : public  BaseBinaryEdge<2, Vector2d, VertexSBAPointXYZ, VertexCam>
                                                                                                                ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp: In member function ‘void g2o::EdgeProjectP2MCRight::computeError()’:
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:55:13: error: ‘VertexSBAPointXYZ’ does not name a type
       const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
             ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:56:60: error: ‘_vertices’ was not declared in this scope
       const VertexCam *cam = static_cast<const VertexCam*>(_vertices[1]);
                                                            ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:61:22: error: ‘point’ was not declared in this scope
       pt.head<3>() = point->estimate();
                      ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:85:7: error: ‘_error’ was not declared in this scope
       _error = perr - _measurement;
       ^
/home/shm/sptam_ws/src/sptam/src/sptam/types_sba_extension.hpp:85:23: error: ‘_measurement’ was not declared in this scope
       _error = perr - _measurement;
                       ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp: In member function ‘G2ODriver::Vertex* G2ODriver::AddVertex(const MapPoint&, bool, bool, G2ODriver::VertexData*)’:
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:103:3: error: ‘VertexSBAPointXYZ’ is not a member of ‘g2o’
   g2o::VertexSBAPointXYZ* v_p = new g2o::VertexSBAPointXYZ();
   ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:103:27: error: ‘v_p’ was not declared in this scope
   g2o::VertexSBAPointXYZ* v_p = new g2o::VertexSBAPointXYZ();
                           ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:103:37: error: expected type-specifier
   g2o::VertexSBAPointXYZ* v_p = new g2o::VertexSBAPointXYZ();
                                     ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp: In static member function ‘static Eigen::Vector3d G2ODriver::GetPoint(g2o::HyperGraph::Vertex&)’:
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:3: error: ‘VertexSBAPointXYZ’ is not a member of ‘g2o’
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
   ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:27: error: ‘point_vertex’ was not declared in this scope
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
                           ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:60: error: ‘VertexSBAPointXYZ’ in namespace ‘g2o’ does not name a type
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
                                                            ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:77: error: expected ‘>’ before ‘&’ token
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
                                                                             ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:77: error: expected ‘(’ before ‘&’ token
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:78: error: expected primary-expression before ‘>’ token
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
                                                                              ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:153:89: error: expected ‘)’ before ‘;’ token
   g2o::VertexSBAPointXYZ& point_vertex = dynamic_cast<g2o::VertexSBAPointXYZ&>( vertex );
                                                                                         ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp: In member function ‘G2ODriver::Edge* G2ODriver::BuildMonoEdgeRight(const std::vector<double>&)’:
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:196:6: error: ‘class g2o::EdgeProjectP2MCRight’ has no member named ‘setMeasurement’
   e->setMeasurement( Eigen::Vector2d(projection[0], projection[1]) );
      ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:197:6: error: ‘class g2o::EdgeProjectP2MCRight’ has no member named ‘information’
   e->information() = Eigen::Matrix2d::Identity();
      ^
/home/shm/sptam_ws/src/sptam/src/sptam/g2o_driver.cpp:198:10: error: cannot convert ‘g2o::EdgeProjectP2MCRight*’ to ‘G2ODriver::Edge* {aka g2o::OptimizableGraph::Edge*}’ in return
   return e;
          ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-int-in-bool-context’
sptam/src/sptam/CMakeFiles/sptam.dir/build.make:283: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/g2o_driver.cpp.o' failed
make[2]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/g2o_driver.cpp.o] Error 1
CMakeFiles/Makefile2:3180: recipe for target 'sptam/src/sptam/CMakeFiles/sptam.dir/all' failed
make[1]: *** [sptam/src/sptam/CMakeFiles/sptam.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 48%] Building CXX object sptam/src/ros/CMakeFiles/sptam_ros.dir/utils/tf_utils.cpp.o
[ 51%] Building CXX object sptam/src/ros/CMakeFiles/sptam_ros.dir/utils/opencv_parsers.cpp.o
[ 53%] Linking CXX shared library /home/shm/sptam_ws/devel/lib/libsptam_ros.so
[ 53%] Built target sptam_ros
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j2 -l2" failed
shm@shm-virtual-machine:~/sptam_ws$ ^C

**Comment by taihup** [comment]
Hi @sunhm415, sorry for the late replay, effectively, it seems to be related with g2o version. Are you using the suggested g2o commits? Please, also check the Eigen version. There is a kwon bug that we couldn't solve yet related to memory management.

Please, also check other issues related with compilation where we have solved similar problems.

**Comment by ysingfun** [comment]
I also encountered the same problem, how can I solve it:
```
/home/pmj/Desktop/loam/project/slambook-master/ch7/pose_estimation_3d2d.cpp: In function ‘void bundleAdjustment(std::vector<cv::Point3_<float> >, std::vector<cv::Point_<float> >, const cv::Mat&, cv::Mat&, cv::Mat&)’:
/home/pmj/Desktop/loam/project/slambook-master/ch7/pose_estimation_3d2d.cpp:194:14: error: ‘VertexSBAPointXYZ’ is not a member of ‘g2o’
         g2o::VertexSBAPointXYZ* point = new g2o::VertexSBAPointXYZ();
              ^~~~~~~~~~~~~~~~~
/home/pmj/Desktop/loam/project/slambook-master/ch7/pose_estimation_3d2d.cpp:194:14: note: suggested alternative: ‘VertexPointXYZ’
         g2o::VertexSBAPointXYZ* point = new g2o::VertexSBAPointXYZ();
              ^~~~~~~~~~~~~~~~~
              VertexPointXYZ
```
@taihup

**Comment by taihup** [comment]
Hi @panmengjia, are you using all the recommended commits and Ubuntu 16.04? One option is to create a docker container.

**Comment by ysingfun** [comment]
Thanks! @taihup 
Really amazing!!!
I search for this `VertexSBAPointXYZ` in [ RainerKuemmerle/g2o](https://github.com/RainerKuemmerle/g2o),But there is no such category.I guess it is very likely that other people have modified the class, but the official source code has not been implemented.

**Comment by taihup** [comment]
you must use the commit (4b9c2f5b68d14ad479457b18c5a2a0bce1541a90) mentioned in the README for the g2o library...

**Comment by ysingfun** [comment]
Thank you, this is very helpful to me!  ! @taihup 
When I execute the following command:
```bash
$ git clone https://github.com/RainerKuemmerle/g2o.git
$ git checkout 4b9c2f5b68d14ad479457b18c5a2a0bce1541a90
$ find -type f | xargs grep "VertexSBAPointXYZ"
```
I did find it `VertexSBAPointXYZ`,as followed:
```bash
./g2o/types/sim3/types_seven_dof_expmap.cpp:  BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSim3Expmap>()
./g2o/types/sim3/types_seven_dof_expmap.cpp:    BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSim3Expmap>() {
./g2o/types/sim3/types_seven_dof_expmap.h:class EdgeSim3ProjectXYZ : public  BaseBinaryEdge<2, Vector2D,  VertexSBAPointXYZ, VertexSim3Expmap>
./g2o/types/sim3/types_seven_dof_expmap.h:      const VertexSBAPointXYZ* v2 = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sim3/types_seven_dof_expmap.h:class EdgeInverseSim3ProjectXYZ : public BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSim3Expmap> {
./g2o/types/sim3/types_seven_dof_expmap.h:    const VertexSBAPointXYZ *v2 = static_cast<const VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_sba.cpp:  G2O_REGISTER_TYPE(VERTEX_XYZ, VertexSBAPointXYZ);
./g2o/types/sba/types_sba.cpp:  VertexSBAPointXYZ::VertexSBAPointXYZ() : BaseVertex<3, Vector3D>()
./g2o/types/sba/types_sba.cpp:  bool VertexSBAPointXYZ::read(std::istream& is)
./g2o/types/sba/types_sba.cpp:  bool VertexSBAPointXYZ::write(std::ostream& os) const
./g2o/types/sba/types_sba.cpp:  BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexCam>()
./g2o/types/sba/types_sba.cpp:    BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexCam>()
./g2o/types/sba/types_sba.cpp:    VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_sba.cpp:    VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_sba.cpp:    VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.cpp:EdgeProjectXYZ2UV::EdgeProjectXYZ2UV() : BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap>() {
./g2o/types/sba/types_six_dof_expmap.cpp:  const VertexSBAPointXYZ * psi = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.cpp:  VertexSBAPointXYZ* vpoint = static_cast<VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.cpp:EdgeProjectXYZ2UVU::EdgeProjectXYZ2UVU() : BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexSE3Expmap>()
./g2o/types/sba/types_six_dof_expmap.cpp:  VertexSBAPointXYZ* vi = static_cast<VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.cpp:EdgeSE3ProjectXYZ::EdgeSE3ProjectXYZ() : BaseBinaryEdge<2, Vector2d, VertexSBAPointXYZ, VertexSE3Expmap>() {
./g2o/types/sba/types_six_dof_expmap.cpp:  VertexSBAPointXYZ *vi = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.cpp:EdgeStereoSE3ProjectXYZ::EdgeStereoSE3ProjectXYZ() : BaseBinaryEdge<3, Vector3d, VertexSBAPointXYZ, VertexSE3Expmap>() {
./g2o/types/sba/types_six_dof_expmap.cpp:  VertexSBAPointXYZ *vi = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_sba.h: class G2O_TYPES_SBA_API VertexSBAPointXYZ : public BaseVertex<3, Vector3D>
./g2o/types/sba/types_sba.h:    VertexSBAPointXYZ();
./g2o/types/sba/types_sba.h: class G2O_TYPES_SBA_API EdgeProjectP2MC : public  BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexCam> 
./g2o/types/sba/types_sba.h:      const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_sba.h: class G2O_TYPES_SBA_API EdgeProjectP2SC : public  BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexCam>
./g2o/types/sba/types_sba.h:      const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_sba.h:      const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:class G2O_TYPES_SBA_API EdgeProjectXYZ2UV : public  BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap>{
./g2o/types/sba/types_six_dof_expmap.h:      const VertexSBAPointXYZ* v2 = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:class G2O_TYPES_SBA_API EdgeProjectXYZ2UVU : public  BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexSE3Expmap>{
./g2o/types/sba/types_six_dof_expmap.h:      const VertexSBAPointXYZ* v2 = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:class EdgeSE3ProjectXYZ : public BaseBinaryEdge<2, Vector2D, VertexSBAPointXYZ, VertexSE3Expmap> {
./g2o/types/sba/types_six_dof_expmap.h:    const VertexSBAPointXYZ *v2 = static_cast<const VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:    const VertexSBAPointXYZ *v2 = static_cast<const VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:class EdgeStereoSE3ProjectXYZ : public BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexSE3Expmap> {
./g2o/types/sba/types_six_dof_expmap.h:    const VertexSBAPointXYZ *v2 = static_cast<const VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/sba/types_six_dof_expmap.h:    const VertexSBAPointXYZ *v2 = static_cast<const VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/icp/types_icp.cpp:    VertexSBAPointXYZ *vp = static_cast<VertexSBAPointXYZ *>(_vertices[0]);
./g2o/types/icp/types_icp.h:  class G2O_TYPES_ICP_API Edge_XYZ_VSC : public  BaseBinaryEdge<3, Vector3D, VertexSBAPointXYZ, VertexSCam>
./g2o/types/icp/types_icp.h:      const VertexSBAPointXYZ *point = static_cast<const VertexSBAPointXYZ*>(_vertices[0]);
./g2o/examples/ba_anchored_inverse_depth/ba_anchored_inverse_depth_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/ba_anchored_inverse_depth/ba_anchored_inverse_depth_demo.cpp:        = new g2o::VertexSBAPointXYZ();
./g2o/examples/ba_anchored_inverse_depth/ba_anchored_inverse_depth_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/ba_anchored_inverse_depth/ba_anchored_inverse_depth_demo.cpp:        = dynamic_cast< g2o::VertexSBAPointXYZ * > (v_it->second);
./g2o/examples/ba/ba_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/ba/ba_demo.cpp:        = new g2o::VertexSBAPointXYZ();
./g2o/examples/ba/ba_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/ba/ba_demo.cpp:        = dynamic_cast< g2o::VertexSBAPointXYZ * > (v_it->second);
./g2o/examples/data_convert/convert_sba_slam3d.cpp:    else if (dynamic_cast<VertexSBAPointXYZ*>(it->second)) {
./g2o/examples/data_convert/convert_sba_slam3d.cpp:      VertexSBAPointXYZ* v = static_cast<VertexSBAPointXYZ*>(it->second);
./g2o/examples/sba/sba_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/sba/sba_demo.cpp:        = new g2o::VertexSBAPointXYZ();
./g2o/examples/sba/sba_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/sba/sba_demo.cpp:        = dynamic_cast< g2o::VertexSBAPointXYZ * > (v_it->second);
./g2o/examples/icp/gicp_sba_demo.cpp:    g2o::VertexSBAPointXYZ * v_p
./g2o/examples/icp/gicp_sba_demo.cpp:        = new g2o::VertexSBAPointXYZ();
```
But I searched for VertexSBAPointXYZ in the search bar of [ RainerKuemmerle/g2o](https://github.com/RainerKuemmerle/g2o), but I didn’t find it. Before that, I had switched to the corresponding commit version(4b9c2f5b68d14ad479457b18c5a2a0bce1541a90).The search results show that there is no such character.You can try searching.
I am very confused about this.

**Comment by taihup** [comment]
Since the commit 4b9c2f5b68d14ad479457b18c5a2a0bce1541a90  is pretty old, they must removed/replaced such type (VertexSBAPointXYZ) from the code. Not 100% sure but Github search could be searching in the current code and not in the whole history.

Please confirm that after doing the checkout compilation error disappear.
