### ISSUE TITLE
Please help me, it's too difficult to solve

### ISSUE THREAD

**Issue by WuHaote** [lrse/sptam#50]
When I use this command  ：rosparam set use_sim_time true

ERROR: Unable to communicate with master!

**Comment by taihup** [comment]
Hi @WuHaote, have you run roscore command in a terminal?

**Comment by WuHaote** [comment]
Thank you, I ran it successfully. It turned out that I ran as many terminals as the little turtle. I also want to know that I finished running this algorithm. I ran the first data set of EUROC, but I didn't know where to find the key frame track file. I was a little confused. Thank you very much.

**Comment by WuHaote** [comment]
Or, did it not generate such a file after it finished running。

**Comment by taihup** [comment]
Check the ~/.ros/ directory after run S-PTAM, it should have a .log file created by S-PTAM. In this log file you can find the pose computed by S-PTAM for each frame among other log information for debugging.

Please check the existing issues, several questions/doubts are already solved or discussed. For example this one was already answered here: [https://github.com/lrse/sptam/issues/19#issuecomment-350592725](https://github.com/lrse/sptam/issues/19#issuecomment-350592725)

**Comment by WuHaote** [comment]
Where are the key frame track files kept?
I want to know.
tycoon

**Comment by WuHaote** [comment]
Forgive me for being stupid, I didn't find the log file.
 and I couldn't see how to get the camera pose file in another question. May I ask what the file name is?

**Comment by taihup** [comment]
What flags are you using to compile S-PTAM? Have you seen it running properly in ROS (for example by observing the trajectory in rviz)? Could you post an screenshot of the trajectory visualized in RVIZ?

**Comment by WuHaote** [comment]
![~KP4_TOPJOX479DQP16XY A](https://user-images.githubusercontent.com/80100608/116082998-ae23fd00-a6ce-11eb-880d-f012643b2a9d.png)
I used s-ptam in ROS,but I really can't find where the track is saved

**Comment by WuHaote** [comment]
Source space:/root/catkin_ws/src
I run four terminals here
【roscore】
【rosbag play --clock output.bag -s 50】
【roslaunch sptam euroc.launch】
【rosrun rviz rviz】

**Comment by taihup** [comment]
mmm It should be inside the ~/.ros directory with the current date and time `YEAR-MM-DD_hh:mm:ss.log`. Could you paste here the content of ~/.ros directory? Example: [https://github.com/lrse/sptam/issues/40#issuecomment-517314546](https://github.com/lrse/sptam/issues/40#issuecomment-517314546)

**Comment by WuHaote** [comment]
Sorry, I didn't notice that ROS has another point. Now I found it. But how can this log be compared with groundturth? Can I compare with evo directly?

**Comment by taihup** [comment]
Yes, you can use evo...
The pose of each frame you can find it in the log with the following labels:
**TRACKED_FRAME_POSE**: in initial camera corrdinate system
**REFINED_CAMERA_POSE**: in the odom coordinate system (in general is the same than the camera coordinate system)

This was already replied here:[https://github.com/lrse/sptam/issues/40#issuecomment-517326552]( https://github.com/lrse/sptam/issues/40#issuecomment-517326552)

**Comment by WuHaote** [comment]
Thanks for your help, I found the final frame pose, but it is not continuous, so I'm going to try to slow it down and try to process each frame. Maybe I'll have problems later, please

**Comment by WuHaote** [comment]
Sorry, I'm bothering you again. I don't know how to convert this final frame pose into a text format that EVO tools can read and write. The true value of EUROC is only eight bits. However, my final frame pose has 12 bits in one frame, plus a string of zeros and ones, which is a bit confusing and I don't know how to convert it.
data is true value ，cat.txt is my final frame pose
![T61GDI0X9MK{EUY~N19PKA2](https://user-images.githubusercontent.com/80100608/116205430-58a02c80-a770-11eb-8b3d-fb5816f7f684.png)
![QYRA25B(F@KG(VT}KZSPZ77](https://user-images.githubusercontent.com/80100608/116205443-5b028680-a770-11eb-9ec8-4c1fea0dd421.png)

**Comment by taihup** [comment]
Observe that first FINAL_FRAME_POSE value is the number of the frame, the next 12 values is the pose and "The string of zeros and ones" that you mentioned belongs to the pose covariance (in this case is the matrix identity). Moreover, to understand the  pose values you can check the code (for example search in the code the keyword: FINAL_FRAME_POSE).
You can take the 12 values related with pose and generated KITTI format pose for example. Evo can process KITTI format.

**Comment by WuHaote** [comment]
I'm sorry, but I still have a problem.
Question 1: Do you mean that the final frame of the log file is klttl data set format, and I need to use evo to convert the log file klttl into eucoc format?
Question 2: Is the file saved by 2：rostopic the log file I saw?
Question 3：evo doesn't seem to be very good at converting klttl format into other formats. Can you provide some good methods?
Question 4: I can't find the keyword FINAL_FRAME_POSE in sptam/src. Can you tell me where it is?

**Comment by taihup** [comment]
Question 1: yes. you can create or modify the S-PTAM output.
Question 2: Not sure if I understand the question. The FINAL_FRAME_POSE  is in KITTI format. The poses that are published in ROS have the format depicted by [geometry_msgs::PoseWithCovarianceStamped](http://docs.ros.org/kinetic/api/geometry_msgs/html/msg/PoseWithCovarianceStamped.html).
Question 3: There are some scripts here: [https://github.com/CIFASIS/dataset-processing/tree/master/data_converters](https://github.com/CIFASIS/dataset-processing/tree/master/data_converters). Maybe they can be useful for you. Otherwise you can create your own script.
Question 4: FINAL_FRAME_POSE is located in: [https://github.com/lrse/sptam/blob/master/src/ros/base_driver.cpp](https://github.com/lrse/sptam/blob/master/src/ros/base_driver.cpp)

**Comment by WuHaote** [comment]
I'm busy with other things recently. Thank you for your patience and reply. You are the fastest writer I have ever seen to reply to information, so I present a star to you. You're a great author. For me, a novice SLAM, I really appreciate it. Perhaps, in the near future, I will trouble you again.

**Comment by taihup** [comment]
I recently uploaded a S-PTAM docker to facilitate its compilation and run. Please check https://cifasis.github.io/sptam. The new code is hosted in https://github.com/CIFASIS/sptam
