### ISSUE TITLE
S-PTAM hangs on "sptam node initialized"

### ISSUE THREAD

**Issue by kubiak54** [lrse/sptam#8]
Hello,
I would appreciate so much your help!
I successfully run your kitti and level7 datasets.
Now I am trying to run my own - playing video file .mp4 with both cameras. I am succesfully running nodes stereo/left/image_raw and camera_info and right nodes as well. Sucessfully running stereo_proc and having rect_images. Everything is just ready but when I run SPTAM it just hangs on "sptam node initialized" forever and nothing happens...Changing number of features, featuers quality, epipolar distance, nothing helps, can you suggest?
Thank you!

**Comment by taihup** [comment]
Hi, What do you mean you are playing your mp4 file? You must use a rosbag file to publish images and camera_info (with the previous calibration of the cameras) messages. Are the stereo images and camera_info messages synchronized?

**Comment by kubiak54** [comment]
I am playing mp4 trough gscam in ROS and everything is working ok - I am publishing calibrated info as well and procesing so have rectified images.
I managed to get it further working - my nodes are just a tiny nsec different so I had to enable approximate_sync=true. Now at this point I am able to get to "Trying to intialize map...
Points initialized from stereo: 15" but nothing happens next - this is the same behaviour as in kitti - I was not able to run it. Only level 7 works totally ok.
But finally I managed to get it working - I had to set use_sim_time=false and connect in TF base_link to camera_1.
But it works so so badly.... what is sim time for? and, if I just have cameras how should I setup TFs in launch file?
Thank you!

**Comment by kubiak54** [comment]
Look at pictures - it makes lots of totally random lines using level7.yaml settings.

![screenshot from 2016-02-17 16 57 00](https://cloud.githubusercontent.com/assets/14558099/13115338/a06d9ac6-d597-11e5-9b30-a235b3e469af.png)
![screenshot from 2016-02-17 16 57 47](https://cloud.githubusercontent.com/assets/14558099/13115339/a06ef98e-d597-11e5-9264-f705b0865875.png)

**Comment by taihup** [comment]
Check ROS documentation for understand use_sim_time [http://wiki.ros.org/Clock](http://wiki.ros.org/Clock). Remember to use the --clock flag in the rosbag when you use_sim_time=true.

Try to reproduce the rosbag with a low frame rate. With a rosbag this is with the option -r. This help when the computer is not so fast. Are you using a i7 Core as recommended?

Maybe the calibration is not so good, or the scene does not have too many features, these are reasons which can cause to S-PTAM working bad. Aslo, the unsynchronized images could impact in S-PTAM but it does not look to be the problem.

Furthermore, if you changes the parameters such as epipolar_distance for example, S-PTAM could have more matches but they could be wrong. This could be the reason that you could initilize points (most of them wrong) and in consequently the tracking is really bad.

To set the TFs properly follow the KITTI example. It is a case where you only have a camera and nothing more, so it must be similar to your case.

**Comment by kubiak54** [comment]
Thank you for your quick response.
My TF is okay.
What I am doing is actually that I have mp4 videos from my 3D camcoder - so I am playing one video in a loop now. Though I do not think there is any problem with it - I managed to generate calibration file which looks ok (by making and playing video of showing pattern from different angles). I am publishing images and infos and processing them - rate is 11 Hz, each image is 960x540 for now and i am running iMac 2010 with i7 processor. Synchronization is okay as well I think - there are just few nsecs.
When running this, is it okay to have sim time = false? (as I am not using rosbag).
The thing is that everything look really okay but tracking is totally messed up - there are even appearing very very long lines and nonsense motion lines.
Can you suggest some settings (maybe other detector, descriptor?) which might be more stable? Or other thing I can try/may be wrong? Or is it possible video is just too hard to be processed for this algorithm?
The same settings works great for level7...
Thank you!!

**Comment by taihup** [comment]
I do not know how do you get the image and camera_info messages from your mp4 video. I suggest you to create a rosbag with the messages (use_sim_time must be false when you record the video / ros messages). Once you have the rosbag, reproduce it with the flag --clock and set to true the use_sim_time parameter. Also, you can check if the images are compressed and del with them with [compressed_image_transport](http://wiki.ros.org/compressed_image_transport)

You can try different extractors and descriptors, and maybe you will find better results. I think the best configuration is GFTT/BRIEF in terms performance.

**Comment by kubiak54** [comment]
It is compressed video stream - unfortunately its not possible for me to use raw format.
I created bag and tried it that way - still no usable tracking.
I uploaded databag here: http://we.tl/zS9xNPaAWZ
It would be so so nice of you if you could take a quick look at it and tell me if its even possible to get some usable data from such bag?
Its compressed bag.
And here, please see attached launch and yaml files I am using and also two ini calibration files I used (no need to use again - image_rect is already in the bag).
[send.tar.gz](https://github.com/lrse/sptam/files/135190/send.tar.gz)

That would be so helpful, thank you so much.

**Comment by taihup** [comment]
Sorry for the late reply, and sorry again because I do not have time to check it. If you make it work post here the answer please.
