### ISSUE TITLE
query regarding feature tracks for multiple frames

### ISSUE THREAD

**Issue by Exception4U** [lrse/sptam#9]
I am wondering if I can extract landmark data such that which landmark (3d point) is present in multiple frames .Or if i can get feature tracks in multiple frames

**Comment by taihup** [comment]
Sorry but I do not understand what you mean. Can you give me more information about what do you want to do and How?

**Comment by taihup** [comment]
If you want to track features from frame to frame (without use the 3D points), you will have to implement this behaviour by your own. S-PTAM was not implemented with this technique in mind.

Let me know if this is what you want to know.

**Comment by Exception4U** [comment]
Sorry for late reply .Actually I need 3d point as landmark and want to figure out that in how many frames that 3d point exist. Are you calculating that information anywhere ?

**Comment by taihup** [comment]
Yes you cando that, check the code of BundleAdjustRecent()  function in [MapMaker.cpp](https://github.com/lrse/sptam/blob/master/src/sptam/MapMaker.cpp).

**Comment by Exception4U** [comment]
with my current understanding of the code flow to get info about presence of 3d points in multiple frames I have added code https://github.com/Exception4U/sptam/blob/master/src/sptam/sptam.cpp#L133 
to get 3d points from left frame and corrosponding 2d point. 

But I have no clue from ho to check weather same 3d point is present in next image because in naxt image 3d points have variation in fraction of its floating point .and also when I print ID of that 3d point many ID are zreo ..is ID not unique for every 3d point and if not how can I uniquely label the same 3d point in map in order that it can be tracked in current frame with somae other frame ?

**Comment by taihup** [comment]
The same ID for differente MapPoints could be a BUG (it was used in a first moment for debugging but now maybe the ID is not well mainteined). However, you can distinguish each MapPoint by its memory location (the pointer), check Map class. In MapMaker.cpp yo can see in BundleAdjustRecent how the same MapPoint is found in differentets keyframes:

```
for( auto& kv : keyFrame->GetMeasurementsLeft() ) {
  if( points.count( kv.first ) ) {
    bInclude = true;
    break;
```
